/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Query Position Return
 */
export class AccountsResponse {
    /**
     * Currency name
     */
    'currency'?: string;
    /**
     * Available Balance
     */
    'available'?: string;
    /**
     * Locked balance
     */
    'locked'?: string;
    /**
     * Token address
     */
    'tokenAddress'?: string;
    /**
     * Blockchain name
     */
    'chain'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'available',
            baseName: 'available',
            type: 'string',
        },
        {
            name: 'locked',
            baseName: 'locked',
            type: 'string',
        },
        {
            name: 'tokenAddress',
            baseName: 'token_address',
            type: 'string',
        },
        {
            name: 'chain',
            baseName: 'chain',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return AccountsResponse.attributeTypeMap;
    }
}
