/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Ad status update request
 */
export class AdsUpdateStatus {
    /**
     * Advertisement ID.
     */
    'advNo': number;
    /**
     * Ad status. `1`: listed; `3`: delisted; `4`: closed.
     */
    'advStatus': AdsUpdateStatus.AdvStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'advNo',
            baseName: 'adv_no',
            type: 'number',
        },
        {
            name: 'advStatus',
            baseName: 'adv_status',
            type: 'AdsUpdateStatus.AdvStatus',
        },
    ];

    static getAttributeTypeMap() {
        return AdsUpdateStatus.attributeTypeMap;
    }
}

export namespace AdsUpdateStatus {
    export enum AdvStatus {
        NUMBER_1 = <any>1,
        NUMBER_3 = <any>3,
        NUMBER_4 = <any>4,
    }
}
