/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StrategyType } from './strategyType';

/**
 * 策略详情数据。
 */
export class AIHubPortfolioDetailData {
    'strategyId': string;
    'strategyType': StrategyType;
    'market': string;
    'status': string;
    /**
     * 基础信息，字段按策略类型动态变化
     */
    'baseInfo': { [key: string]: string };
    /**
     * 指标信息，字段按策略类型动态变化
     */
    'metrics': { [key: string]: string };
    /**
     * 仓位或持仓信息，字段按策略类型动态变化
     */
    'position'?: { [key: string]: string } | null;
    'stopSupported': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'strategyId',
            baseName: 'strategy_id',
            type: 'string',
        },
        {
            name: 'strategyType',
            baseName: 'strategy_type',
            type: 'StrategyType',
        },
        {
            name: 'market',
            baseName: 'market',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'baseInfo',
            baseName: 'base_info',
            type: '{ [key: string]: string; }',
        },
        {
            name: 'metrics',
            baseName: 'metrics',
            type: '{ [key: string]: string; }',
        },
        {
            name: 'position',
            baseName: 'position',
            type: '{ [key: string]: string; }',
        },
        {
            name: 'stopSupported',
            baseName: 'stop_supported',
            type: 'boolean',
        },
    ];

    static getAttributeTypeMap() {
        return AIHubPortfolioDetailData.attributeTypeMap;
    }
}
