/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Strategy detail base info.
 */
export class AIHubPortfolioBaseInfo {
    'strategyName': string;
    /**
     * Created time
     */
    'createdAt': string;
    /**
     * Runtime duration in seconds.
     */
    'runningDuration': number;
    'investAmount': string;
    'totalProfit': string;
    'profitRate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'strategyName',
            baseName: 'strategy_name',
            type: 'string',
        },
        {
            name: 'createdAt',
            baseName: 'created_at',
            type: 'string',
        },
        {
            name: 'runningDuration',
            baseName: 'running_duration',
            type: 'number',
        },
        {
            name: 'investAmount',
            baseName: 'invest_amount',
            type: 'string',
        },
        {
            name: 'totalProfit',
            baseName: 'total_profit',
            type: 'string',
        },
        {
            name: 'profitRate',
            baseName: 'profit_rate',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return AIHubPortfolioBaseInfo.attributeTypeMap;
    }
}
