/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AIHubPortfolioDetailData } from './aIHubPortfolioDetailData';

/**
 * 查询策略详情成功时的响应体。
 */
export class AIHubPortfolioDetailSuccessResponse {
    'code': number;
    'message': string;
    'data': AIHubPortfolioDetailData;
    'traceId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'AIHubPortfolioDetailData',
        },
        {
            name: 'traceId',
            baseName: 'trace_id',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return AIHubPortfolioDetailSuccessResponse.attributeTypeMap;
    }
}
