/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 领取奖励结果
 */
export class ApiResponseExSkillClaimRewardRespData {
    /**
     * 是否为 m 选 n 奖池任务。为 true 时仅提示跳转，不实际发奖
     */
    'hasMNTask'?: boolean;
    /**
     * 卡券奖励全称。非卡券奖励或无法解析时为空字符串
     */
    'couponFullName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'hasMNTask',
            baseName: 'has_m_n_task',
            type: 'boolean',
        },
        {
            name: 'couponFullName',
            baseName: 'coupon_full_name',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return ApiResponseExSkillClaimRewardRespData.attributeTypeMap;
    }
}
