/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConvertCurrenciesV2Item } from './convertCurrenciesV2Item';
import { Recommend } from './recommend';
import { RecommendV2Strategy } from './recommendV2Strategy';

export class AssetSwapFrontend {
    'assetEvaluateRange': Array<number>;
    'bannerReappearIntervalHours': number;
    'convertCurrencies': Array<string>;
    'convertCurrenciesV2': Array<ConvertCurrenciesV2Item>;
    /**
     * 字符串键到字符串值的映射，对应 Go 的 map[string]string。
     */
    '_default': { [key: string]: string };
    'maxSelectCurrencies': number;
    'minEvaluateValue': string;
    'recommend': Recommend;
    /**
     * 策略分组键到 RecommendV2Strategy 列表的映射。
     */
    'recommendV2': { [key: string]: Array<RecommendV2Strategy> };
    'titleTips': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'assetEvaluateRange',
            baseName: 'asset_evaluate_range',
            type: 'Array<number>',
        },
        {
            name: 'bannerReappearIntervalHours',
            baseName: 'banner_reappear_interval_hours',
            type: 'number',
        },
        {
            name: 'convertCurrencies',
            baseName: 'convert_currencies',
            type: 'Array<string>',
        },
        {
            name: 'convertCurrenciesV2',
            baseName: 'convert_currencies_v2',
            type: 'Array<ConvertCurrenciesV2Item>',
        },
        {
            name: '_default',
            baseName: 'default',
            type: '{ [key: string]: string; }',
        },
        {
            name: 'maxSelectCurrencies',
            baseName: 'max_select_currencies',
            type: 'number',
        },
        {
            name: 'minEvaluateValue',
            baseName: 'min_evaluate_value',
            type: 'string',
        },
        {
            name: 'recommend',
            baseName: 'recommend',
            type: 'Recommend',
        },
        {
            name: 'recommendV2',
            baseName: 'recommend_v2',
            type: '{ [key: string]: Array<RecommendV2Strategy>; }',
        },
        {
            name: 'titleTips',
            baseName: 'title_tips',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return AssetSwapFrontend.attributeTypeMap;
    }
}
