/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class AutoInvestMinInvestAmountItems {
    /**
     * Currency
     */
    'asset': string;
    /**
     * Ratio，e.g.100
     */
    'ratio': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'asset',
            baseName: 'asset',
            type: 'string',
        },
        {
            name: 'ratio',
            baseName: 'ratio',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return AutoInvestMinInvestAmountItems.attributeTypeMap;
    }
}
