/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CandyDropV4TaskCd03 {
    /**
     * 任务主标题
     */
    'taskName'?: string;
    /**
     * 任务副标题，无则返回 -
     */
    'taskDesc'?: string;
    /**
     * 专属任务标签文案，未配置则返回 -
     */
    'exclusiveLabel'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'taskName',
            baseName: 'task_name',
            type: 'string',
        },
        {
            name: 'taskDesc',
            baseName: 'task_desc',
            type: 'string',
        },
        {
            name: 'exclusiveLabel',
            baseName: 'exclusive_label',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CandyDropV4TaskCd03.attributeTypeMap;
    }
}
