/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CandyDropV4AirdropRecordCd06 {
    /**
     * Product Name
     */
    'currency'?: string;
    /**
     * Airdrop time (UTC format)
     */
    'airdropTime'?: string;
    /**
     * Airdrop rewards
     */
    'rewards'?: string;
    /**
     * Automatic exchange amount
     */
    'convertAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'airdropTime',
            baseName: 'airdrop_time',
            type: 'string',
        },
        {
            name: 'rewards',
            baseName: 'rewards',
            type: 'string',
        },
        {
            name: 'convertAmount',
            baseName: 'convert_amount',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CandyDropV4AirdropRecordCd06.attributeTypeMap;
    }
}
