/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CandyDropV4PrizePoolCd03 } from './candyDropV4PrizePoolCd03';

export class CandyDropV4ActivityRulesCd03 {
    /**
     * Project/currency name
     */
    'currency'?: string;
    /**
     * total prize pool
     */
    'totalRewards'?: string;
    /**
     * Event start time (UTC formatted)
     */
    'startTime'?: string;
    /**
     * Event end time (UTC format)
     */
    'endTime'?: string;
    /**
     * Prize pool list
     */
    'prizePools'?: Array<CandyDropV4PrizePoolCd03>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'totalRewards',
            baseName: 'total_rewards',
            type: 'string',
        },
        {
            name: 'startTime',
            baseName: 'start_time',
            type: 'string',
        },
        {
            name: 'endTime',
            baseName: 'end_time',
            type: 'string',
        },
        {
            name: 'prizePools',
            baseName: 'prize_pools',
            type: 'Array<CandyDropV4PrizePoolCd03>',
        },
    ];

    static getAttributeTypeMap() {
        return CandyDropV4ActivityRulesCd03.attributeTypeMap;
    }
}
