/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Chase order detail or list item
 */
export class ChaseOrder {
    'id'?: string;
    'user'?: string;
    'contract'?: string;
    'settle'?: string;
    /**
     * Total size in contracts; positive for buy, negative for sell
     */
    'amount'?: string;
    'priceLimit'?: string;
    'reduceOnly'?: boolean;
    'text'?: string;
    'createTime'?: number;
    'finishTime'?: number;
    /**
     * Raw status enum
     */
    'originalStatus'?: number;
    /**
     * Simplified status, e.g. open / finished
     */
    'status'?: string;
    'reason'?: string;
    'fillAmount'?: string;
    'averageFillPrice'?: string;
    'suborderId'?: string;
    'isDualMode'?: boolean;
    'sideLabel'?: string;
    'positionSideOutput'?: string;
    'chasePrice'?: string;
    'intervalSec'?: number;
    'updatedAt'?: number;
    'suborderPrice'?: string;
    'suborderOngoing'?: boolean;
    'suborderFinishAs'?: string;
    /**
     * PriceType enum: 1 latest, 2 index, 3 mark
     */
    'priceType'?: number;
    'priceGapType'?: string;
    'priceGapValue'?: string;
    'statusCode'?: string;
    /**
     * Creation time (seconds.microseconds)
     */
    'createTimePrecise'?: string;
    'finishTimePrecise'?: string;
    'posMarginMode'?: string;
    'positionMode'?: string;
    'leverage'?: string;
    'errorLabel'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'user',
            baseName: 'user',
            type: 'string',
        },
        {
            name: 'contract',
            baseName: 'contract',
            type: 'string',
        },
        {
            name: 'settle',
            baseName: 'settle',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'priceLimit',
            baseName: 'price_limit',
            type: 'string',
        },
        {
            name: 'reduceOnly',
            baseName: 'reduce_only',
            type: 'boolean',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
        {
            name: 'finishTime',
            baseName: 'finish_time',
            type: 'number',
        },
        {
            name: 'originalStatus',
            baseName: 'original_status',
            type: 'number',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'reason',
            baseName: 'reason',
            type: 'string',
        },
        {
            name: 'fillAmount',
            baseName: 'fill_amount',
            type: 'string',
        },
        {
            name: 'averageFillPrice',
            baseName: 'average_fill_price',
            type: 'string',
        },
        {
            name: 'suborderId',
            baseName: 'suborder_id',
            type: 'string',
        },
        {
            name: 'isDualMode',
            baseName: 'is_dual_mode',
            type: 'boolean',
        },
        {
            name: 'sideLabel',
            baseName: 'side_label',
            type: 'string',
        },
        {
            name: 'positionSideOutput',
            baseName: 'position_side_output',
            type: 'string',
        },
        {
            name: 'chasePrice',
            baseName: 'chase_price',
            type: 'string',
        },
        {
            name: 'intervalSec',
            baseName: 'interval_sec',
            type: 'number',
        },
        {
            name: 'updatedAt',
            baseName: 'updated_at',
            type: 'number',
        },
        {
            name: 'suborderPrice',
            baseName: 'suborder_price',
            type: 'string',
        },
        {
            name: 'suborderOngoing',
            baseName: 'suborder_ongoing',
            type: 'boolean',
        },
        {
            name: 'suborderFinishAs',
            baseName: 'suborder_finish_as',
            type: 'string',
        },
        {
            name: 'priceType',
            baseName: 'price_type',
            type: 'number',
        },
        {
            name: 'priceGapType',
            baseName: 'price_gap_type',
            type: 'string',
        },
        {
            name: 'priceGapValue',
            baseName: 'price_gap_value',
            type: 'string',
        },
        {
            name: 'statusCode',
            baseName: 'status_code',
            type: 'string',
        },
        {
            name: 'createTimePrecise',
            baseName: 'create_time_precise',
            type: 'string',
        },
        {
            name: 'finishTimePrecise',
            baseName: 'finish_time_precise',
            type: 'string',
        },
        {
            name: 'posMarginMode',
            baseName: 'pos_margin_mode',
            type: 'string',
        },
        {
            name: 'positionMode',
            baseName: 'position_mode',
            type: 'string',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
        {
            name: 'errorLabel',
            baseName: 'error_label',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return ChaseOrder.attributeTypeMap;
    }
}
