/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContractMartingaleDirection } from './contractMartingaleDirection';

/**
 * 合约马丁策略的创建参数。
 */
export class ContractMartingaleCreateParams {
    'investAmount': string;
    'priceDeviation': string;
    'maxOrders': number;
    'takeProfitRatio': string;
    'direction': ContractMartingaleDirection;
    'leverage': string;
    'stopLossPrice'?: string;
    'profitSharingRatio'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'investAmount',
            baseName: 'invest_amount',
            type: 'string',
        },
        {
            name: 'priceDeviation',
            baseName: 'price_deviation',
            type: 'string',
        },
        {
            name: 'maxOrders',
            baseName: 'max_orders',
            type: 'number',
        },
        {
            name: 'takeProfitRatio',
            baseName: 'take_profit_ratio',
            type: 'string',
        },
        {
            name: 'direction',
            baseName: 'direction',
            type: 'ContractMartingaleDirection',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
        {
            name: 'stopLossPrice',
            baseName: 'stop_loss_price',
            type: 'string',
        },
        {
            name: 'profitSharingRatio',
            baseName: 'profit_sharing_ratio',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return ContractMartingaleCreateParams.attributeTypeMap;
    }
}
