/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ContractStat {
    /**
     * Stat timestamp
     */
    'time'?: number;
    /**
     * Long/short taker ratio
     */
    'lsrTaker'?: number;
    /**
     * Long/short position user ratio
     */
    'lsrAccount'?: number;
    /**
     * Long liquidation size (contracts)
     */
    'longLiqSize'?: string;
    /**
     * Long liquidation amount (base currency)
     */
    'longLiqAmount'?: number;
    /**
     * Long liquidation volume (quote currency)
     */
    'longLiqUsd'?: number;
    /**
     * Long liquidations in quote currency; USDT settlement: long_liq_size × multiplier × mark price
     */
    'longLiqUsdNew'?: number;
    /**
     * Short liquidation size (contracts)
     */
    'shortLiqSize'?: string;
    /**
     * Short liquidation amount (base currency)
     */
    'shortLiqAmount'?: number;
    /**
     * Short liquidation volume (quote currency)
     */
    'shortLiqUsd'?: number;
    /**
     * Short liquidations in quote currency; USDT settlement: short_liq_size × multiplier × mark price
     */
    'shortLiqUsdNew'?: number;
    /**
     * Total open interest size (contracts)
     */
    'openInterest'?: string;
    /**
     * Total open interest volume (quote currency)
     */
    'openInterestUsd'?: number;
    /**
     * Top trader long/short account ratio
     */
    'topLsrAccount'?: number;
    /**
     * Top trader long/short position ratio
     */
    'topLsrSize'?: string;
    /**
     * Mark price
     */
    'markPrice'?: number;
    /**
     * Top long open interest (contracts)
     */
    'topLongSize'?: string;
    /**
     * Top short open interest (contracts)
     */
    'topShortSize'?: string;
    /**
     * Long taker trade volume (contracts)
     */
    'longTakerSize'?: string;
    /**
     * Short taker trade volume (contracts)
     */
    'shortTakerSize'?: string;
    /**
     * Number of top long accounts (large holders)
     */
    'topLongAccount'?: number;
    /**
     * Number of top short accounts (large holders)
     */
    'topShortAccount'?: number;
    /**
     * Number of users holding long positions
     */
    'longUsers'?: string;
    /**
     * Number of users holding short positions
     */
    'shortUsers'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'time',
            baseName: 'time',
            type: 'number',
        },
        {
            name: 'lsrTaker',
            baseName: 'lsr_taker',
            type: 'number',
        },
        {
            name: 'lsrAccount',
            baseName: 'lsr_account',
            type: 'number',
        },
        {
            name: 'longLiqSize',
            baseName: 'long_liq_size',
            type: 'string',
        },
        {
            name: 'longLiqAmount',
            baseName: 'long_liq_amount',
            type: 'number',
        },
        {
            name: 'longLiqUsd',
            baseName: 'long_liq_usd',
            type: 'number',
        },
        {
            name: 'longLiqUsdNew',
            baseName: 'long_liq_usd_new',
            type: 'number',
        },
        {
            name: 'shortLiqSize',
            baseName: 'short_liq_size',
            type: 'string',
        },
        {
            name: 'shortLiqAmount',
            baseName: 'short_liq_amount',
            type: 'number',
        },
        {
            name: 'shortLiqUsd',
            baseName: 'short_liq_usd',
            type: 'number',
        },
        {
            name: 'shortLiqUsdNew',
            baseName: 'short_liq_usd_new',
            type: 'number',
        },
        {
            name: 'openInterest',
            baseName: 'open_interest',
            type: 'string',
        },
        {
            name: 'openInterestUsd',
            baseName: 'open_interest_usd',
            type: 'number',
        },
        {
            name: 'topLsrAccount',
            baseName: 'top_lsr_account',
            type: 'number',
        },
        {
            name: 'topLsrSize',
            baseName: 'top_lsr_size',
            type: 'string',
        },
        {
            name: 'markPrice',
            baseName: 'mark_price',
            type: 'number',
        },
        {
            name: 'topLongSize',
            baseName: 'top_long_size',
            type: 'string',
        },
        {
            name: 'topShortSize',
            baseName: 'top_short_size',
            type: 'string',
        },
        {
            name: 'longTakerSize',
            baseName: 'long_taker_size',
            type: 'string',
        },
        {
            name: 'shortTakerSize',
            baseName: 'short_taker_size',
            type: 'string',
        },
        {
            name: 'topLongAccount',
            baseName: 'top_long_account',
            type: 'number',
        },
        {
            name: 'topShortAccount',
            baseName: 'top_short_account',
            type: 'number',
        },
        {
            name: 'longUsers',
            baseName: 'long_users',
            type: 'string',
        },
        {
            name: 'shortUsers',
            baseName: 'short_users',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return ContractStat.attributeTypeMap;
    }
}
