/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Futures contract details
 */
export class ContractDetailDataList {
    /**
     * Trading symbol code
     */
    'symbol'?: string;
    /**
     * Trading symbol description
     */
    'symbolDesc'?: string;
    /**
     * Category name
     */
    'categoryName'?: string;
    /**
     * Contract Volume
     */
    'contractVolume'?: string;
    /**
     * Settle currency
     */
    'settlementCurrency'?: string;
    /**
     * Maximum Order Volume
     */
    'maxOrderVolume'?: string;
    /**
     * Minimum Order Volume
     */
    'minOrderVolume'?: string;
    /**
     * Position leverage
     */
    'leverage'?: string;
    /**
     * Price precision (decimal places)
     */
    'pricePrecision'?: number;
    /**
     * Stop Loss Price Level
     */
    'priceSlLevel'?: string;
    /**
     * Swap Cost Type
     */
    'swapCostType'?: string;
    /**
     * Buy Swap Cost Rate
     */
    'buySwapCostRate'?: string;
    /**
     * Sell Swap Cost Rate
     */
    'sellSwapCostRate'?: string;
    /**
     * 3-Day Swap Cost
     */
    'swapCost3day'?: string;
    /**
     * Trading Timezone
     */
    'tradeTimezone'?: string;
    /**
     * Trading mode code (0=disabled, 1=long only, 2=short only, 3=close only, 4=full trading access)
     */
    'tradeMode'?: string;
    /**
     * Symbol icon URL
     */
    'iconLink'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'symbolDesc',
            baseName: 'symbol_desc',
            type: 'string',
        },
        {
            name: 'categoryName',
            baseName: 'category_name',
            type: 'string',
        },
        {
            name: 'contractVolume',
            baseName: 'contract_volume',
            type: 'string',
        },
        {
            name: 'settlementCurrency',
            baseName: 'settlement_currency',
            type: 'string',
        },
        {
            name: 'maxOrderVolume',
            baseName: 'max_order_volume',
            type: 'string',
        },
        {
            name: 'minOrderVolume',
            baseName: 'min_order_volume',
            type: 'string',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
        {
            name: 'pricePrecision',
            baseName: 'price_precision',
            type: 'number',
        },
        {
            name: 'priceSlLevel',
            baseName: 'price_sl_level',
            type: 'string',
        },
        {
            name: 'swapCostType',
            baseName: 'swap_cost_type',
            type: 'string',
        },
        {
            name: 'buySwapCostRate',
            baseName: 'buy_swap_cost_rate',
            type: 'string',
        },
        {
            name: 'sellSwapCostRate',
            baseName: 'sell_swap_cost_rate',
            type: 'string',
        },
        {
            name: 'swapCost3day',
            baseName: 'swap_cost_3day',
            type: 'string',
        },
        {
            name: 'tradeTimezone',
            baseName: 'trade_timezone',
            type: 'string',
        },
        {
            name: 'tradeMode',
            baseName: 'trade_mode',
            type: 'string',
        },
        {
            name: 'iconLink',
            baseName: 'icon_link',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return ContractDetailDataList.attributeTypeMap;
    }
}
