/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CreateTrailOrder {
    /**
     * Contract name
     */
    'contract': string;
    /**
     * Trading quantity in contracts, positive for buy, negative for sell
     */
    'amount': string;
    /**
     * Activation price, 0 means trigger immediately
     */
    'activationPrice'?: string;
    /**
     * true: activate when market price >= activation price, false: <= activation price
     */
    'isGte'?: boolean;
    /**
     * Activation price type: 1-latest price, 2-index price, 3-mark price
     */
    'priceType'?: CreateTrailOrder.PriceType;
    /**
     * Callback ratio or price distance, e.g., `0.1` or `0.1%`
     */
    'priceOffset'?: string;
    /**
     * Whether reduce only
     */
    'reduceOnly'?: boolean;
    /**
     * Whether bound to a position (if position_related = true (position-related), then reduce_only must also be true)
     */
    'positionRelated'?: boolean;
    /**
     * 订单自定义信息，可选字段。用于标识订单来源或设置用户自定义 ID。  **如果非空**，必须满足以下规则之一：  **1. 内部保留字段（标识订单来源）**： - `apiv4`: API 调用 **2. 用户自定义字段（设置自定义 ID）**： - 必须以 `t-` 开头 - `t-` 后面的内容长度不能超过 28 字节 - 只能包含：数字、字母、下划线(_)、中划线(-) 或者点(.) - 示例：`t-my-order-001`、`t-trail_2024.01`  **注意**：用户自定义字段不能与内部保留字段冲突。
     */
    'text'?: string;
    /**
     * Position margin mode: isolated/cross
     */
    'posMarginMode'?: string;
    /**
     * Position mode: single, dual, and dual_plus
     */
    'positionMode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'contract',
            baseName: 'contract',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'activationPrice',
            baseName: 'activation_price',
            type: 'string',
        },
        {
            name: 'isGte',
            baseName: 'is_gte',
            type: 'boolean',
        },
        {
            name: 'priceType',
            baseName: 'price_type',
            type: 'CreateTrailOrder.PriceType',
        },
        {
            name: 'priceOffset',
            baseName: 'price_offset',
            type: 'string',
        },
        {
            name: 'reduceOnly',
            baseName: 'reduce_only',
            type: 'boolean',
        },
        {
            name: 'positionRelated',
            baseName: 'position_related',
            type: 'boolean',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
        {
            name: 'posMarginMode',
            baseName: 'pos_margin_mode',
            type: 'string',
        },
        {
            name: 'positionMode',
            baseName: 'position_mode',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CreateTrailOrder.attributeTypeMap;
    }
}

export namespace CreateTrailOrder {
    export enum PriceType {
        NUMBER_1 = <any>1,
        NUMBER_2 = <any>2,
        NUMBER_3 = <any>3,
    }
}
