/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 下单请求体
 */
export class CrossexOrderRequest {
    /**
     * Client-defined Order ID, supports letters (a-z), numbers (0-9), symbols (-, _) only
     */
    'text'?: string;
    /**
     * 唯一标识 Exchange_Business_Base_Counter 示例： 如果您想在BINANCE交易所上为ADA/USDT交易对下现货订单，您可以使用这样的唯一标识符：`BINANCE_SPOT_ADA_USDT`; 如果您想在OKX交易所上为ADA/USDT交易对下U本位永续合约订单，您可以使用这样的唯一标识符：`OKX_FUTURE_ADA_USDT`; 如果您想在GATE交易所上为ADA/USDT交易对下现货杠杆订单，您可以使用这样的唯一标识符：`GATE_MARGIN_ADA_USDT`; 如果您想在BYBIT交易所上为ADA/USDT交易对下现货订单，您可以使用这样的唯一标识符：`BYBIT_SPOT_ADA_USDT`; 目前支持三种订单：现货订单、U本位永续合约订单和现货杠杆订单, BYBIT暂不支持现货杠杆订单
     */
    'symbol': string;
    /**
     * BUY, SELL
     */
    'side': CrossexOrderRequest.Side;
    /**
     * Order type (default: `LIMIT`; supported types: `LIMIT`, `MARKET`)
     */
    'type'?: CrossexOrderRequest.Type;
    /**
     * Default GTC, supports enumerated types: GTC, IOC, FOK, POC GTC: GoodTillCancelled IOC: ImmediateOrCancelled FOK: FillOrKill POC: PendingOrCancelled or PostOnly
     */
    'timeInForce'?: CrossexOrderRequest.TimeInForce;
    /**
     * Order quantity (required unless spot market buy)
     */
    'qty'?: string;
    /**
     * Limit Order Price (Required for Limit Orders)
     */
    'price'?: string;
    /**
     * Order quote quantity; required for spot and margin market buy orders
     */
    'quoteQty'?: string;
    /**
     * Reduce-only: `true` or `false`
     */
    'reduceOnly'?: CrossexOrderRequest.ReduceOnly;
    /**
     * Position side: `NONE`, `LONG`, `SHORT` Defaults to `NONE` (single position mode) if not specified
     */
    'positionSide'?: CrossexOrderRequest.PositionSide;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'CrossexOrderRequest.Side',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'CrossexOrderRequest.Type',
        },
        {
            name: 'timeInForce',
            baseName: 'time_in_force',
            type: 'CrossexOrderRequest.TimeInForce',
        },
        {
            name: 'qty',
            baseName: 'qty',
            type: 'string',
        },
        {
            name: 'price',
            baseName: 'price',
            type: 'string',
        },
        {
            name: 'quoteQty',
            baseName: 'quote_qty',
            type: 'string',
        },
        {
            name: 'reduceOnly',
            baseName: 'reduce_only',
            type: 'CrossexOrderRequest.ReduceOnly',
        },
        {
            name: 'positionSide',
            baseName: 'position_side',
            type: 'CrossexOrderRequest.PositionSide',
        },
    ];

    static getAttributeTypeMap() {
        return CrossexOrderRequest.attributeTypeMap;
    }
}

export namespace CrossexOrderRequest {
    export enum Side {
        BUY = <any>'BUY',
        SELL = <any>'SELL',
    }
    export enum Type {
        LIMIT = <any>'LIMIT',
        MARKET = <any>'MARKET',
    }
    export enum TimeInForce {
        GTC = <any>'GTC',
        IOC = <any>'IOC',
        FOK = <any>'FOK',
        POC = <any>'POC',
    }
    export enum ReduceOnly {
        True = <any>'true',
        False = <any>'false',
    }
    export enum PositionSide {
        LONG = <any>'LONG',
        SHORT = <any>'SHORT',
        NONE = <any>'NONE',
    }
}
