/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class CrossexOrder {
    /**
     * User ID
     */
    'userId': string;
    /**
     * Order ID
     */
    'orderId': string;
    /**
     * Client-defined order ID.
     */
    'text': string;
    /**
     * Order status:  NEW: Validated and queued to be sent to the exchange.  OPEN: Resting on the exchange order book.  PARTIALLY_FILLED: Partially filled.  FILLED: Fully filled.  FAIL: CrossEx internal validation failed; see the `reason` field for details.  REJECT: Rejected by the exchange; see the `reason` field for details.
     */
    'state': string;
    /**
     * Unique trading pair identifiers, e.g. `BINANCE_SPOT_BTC_USDT`, `BINANCE_FUTURE_BTC_USDT`.
     */
    'symbol': string;
    /**
     * Side (`BUY` buy / `SELL` sell).
     */
    'side': string;
    /**
     * Order type (`LIMIT` limit / `MARKET` market).
     */
    'type': string;
    /**
     * Order attributes (`COMMON` normal / `LIQ` liquidation takeover / `REDUCE` liquidation reduction / `ADL` auto-deleverage / `SETTLEMENT` delisting settlement).
     */
    'attribute': string;
    /**
     * Venue bucket (`BINANCE` / `OKX` / `GATE` / `BYBIT` / `KRAKEN` / `HYPERLIQUID`).
     */
    'exchangeType': string;
    /**
     * Business type (`SPOT` Spot / `FUTURE` Futures / `MARGIN` Margin).
     */
    'businessType': string;
    /**
     * Order quantity in the base currency.
     */
    'qty': string;
    /**
     * Order quantity in the quote currency.
     */
    'quoteQty': string;
    /**
     * Order price.
     */
    'price': string;
    /**
     * Time in force (default `GTC`; enum: `GTC` / `IOC` / `FOK` / `POC`).
     */
    'timeInForce': string;
    /**
     * Filled base amount.
     */
    'executedQty': string;
    /**
     * Filled quote amount.
     */
    'executedAmount': string;
    /**
     * Average Filled Price
     */
    'executedAvgPrice': string;
    /**
     * Fee currency
     */
    'feeCoin': string;
    /**
     * Fee amount.
     */
    'fee': string;
    /**
     * Reduce-only order (`\"true\"` or `\"false\"`).
     */
    'reduceOnly': string;
    /**
     * Order leverage multiplier.
     */
    'leverage': string;
    /**
     * Failure reason description.
     */
    'reason': string;
    /**
     * Base quantity of the latest fill.
     */
    'lastExecutedQty': string;
    /**
     * Price of the latest fill.
     */
    'lastExecutedPrice': string;
    /**
     * Quote amount of the latest fill.
     */
    'lastExecutedAmount': string;
    /**
     * Position side (`NONE` flat / `LONG` long / `SHORT` short).
     */
    'positionSide': string;
    /**
     * Created time
     */
    'createTime': string;
    /**
     * Update time
     */
    'updateTime': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'userId',
            baseName: 'user_id',
            type: 'string',
        },
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'string',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
        {
            name: 'state',
            baseName: 'state',
            type: 'string',
        },
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'attribute',
            baseName: 'attribute',
            type: 'string',
        },
        {
            name: 'exchangeType',
            baseName: 'exchange_type',
            type: 'string',
        },
        {
            name: 'businessType',
            baseName: 'business_type',
            type: 'string',
        },
        {
            name: 'qty',
            baseName: 'qty',
            type: 'string',
        },
        {
            name: 'quoteQty',
            baseName: 'quote_qty',
            type: 'string',
        },
        {
            name: 'price',
            baseName: 'price',
            type: 'string',
        },
        {
            name: 'timeInForce',
            baseName: 'time_in_force',
            type: 'string',
        },
        {
            name: 'executedQty',
            baseName: 'executed_qty',
            type: 'string',
        },
        {
            name: 'executedAmount',
            baseName: 'executed_amount',
            type: 'string',
        },
        {
            name: 'executedAvgPrice',
            baseName: 'executed_avg_price',
            type: 'string',
        },
        {
            name: 'feeCoin',
            baseName: 'fee_coin',
            type: 'string',
        },
        {
            name: 'fee',
            baseName: 'fee',
            type: 'string',
        },
        {
            name: 'reduceOnly',
            baseName: 'reduce_only',
            type: 'string',
        },
        {
            name: 'leverage',
            baseName: 'leverage',
            type: 'string',
        },
        {
            name: 'reason',
            baseName: 'reason',
            type: 'string',
        },
        {
            name: 'lastExecutedQty',
            baseName: 'last_executed_qty',
            type: 'string',
        },
        {
            name: 'lastExecutedPrice',
            baseName: 'last_executed_price',
            type: 'string',
        },
        {
            name: 'lastExecutedAmount',
            baseName: 'last_executed_amount',
            type: 'string',
        },
        {
            name: 'positionSide',
            baseName: 'position_side',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'string',
        },
        {
            name: 'updateTime',
            baseName: 'update_time',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return CrossexOrder.attributeTypeMap;
    }
}
