/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class DepositRecord {
    /**
     * Record ID
     */
    'id'?: string;
    /**
     * Hash record of the withdrawal
     */
    'txid'?: string;
    /**
     * Operation time
     */
    'timestamp'?: string;
    /**
     * Token amount
     */
    'amount': string;
    /**
     * Currency name
     */
    'currency': string;
    /**
     * Withdrawal address. Required for withdrawals
     */
    'address'?: string;
    /**
     * Additional remarks with regards to the withdrawal
     */
    'memo'?: string;
    /**
     * Transaction Status  - BLOCKED: Deposit Blocked - DEP_CREDITED: Deposit Credited, Withdrawal Pending Unlock - DONE: Funds Credited to Spot Account - INVALID: Invalid Transaction - MANUAL: Manual Review Required - PEND: Processing - REVIEW: Under Compliance Review - TRACK: Tracking Block Confirmations, Pending Spot Account Credit
     */
    'status'?: string;
    /**
     * Name of the chain used in withdrawals
     */
    'chain': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'txid',
            baseName: 'txid',
            type: 'string',
        },
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'address',
            baseName: 'address',
            type: 'string',
        },
        {
            name: 'memo',
            baseName: 'memo',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'chain',
            baseName: 'chain',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return DepositRecord.attributeTypeMap;
    }
}
