/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseResponse } from './baseResponse';
import { Eligibility } from './eligibility';
import { EligibilityResponseAllOf } from './eligibilityResponseAllOf';

export class EligibilityResponse {
    /**
     * Error Code, 0 Indicates Success
     */
    'code': number;
    /**
     * Error message description
     */
    'message': string;
    'data': Eligibility;
    /**
     * Unix timestamp
     */
    'timestamp': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'Eligibility',
        },
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return EligibilityResponse.attributeTypeMap;
    }
}
