/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Fixed-term earn product
 */
export class FixedTermProduct {
    /**
     * Product ID
     */
    'id'?: number;
    /**
     * Product name
     */
    'name'?: string;
    /**
     * Currency
     */
    'asset'?: string;
    /**
     * Lock-up period (in days)
     */
    'lockUpPeriod'?: number;
    /**
     * Minimum earn amount
     */
    'minLendAmount'?: string;
    /**
     * User maximum earn limit
     */
    'userMaxLendAmount'?: string;
    /**
     * Platform earn limit
     */
    'totalLendAmount'?: string;
    /**
     * Annual interest rate
     */
    'yearRate'?: string;
    /**
     * Product type: 1 for regular, 2 for VIP
     */
    'type'?: number;
    /**
     * Whether early redemption is supported: 0 for not supported, 1 for supported
     */
    'preRedeem'?: number;
    /**
     * Whether auto-renewal is supported: 0 for not supported, 1 for supported
     */
    'reinvest'?: number;
    /**
     * Whether fixed-to-flexible conversion is supported: 0 for not supported, 1 for supported
     */
    'redeemAccount'?: number;
    /**
     * Minimum VIP level requirement, 0-16, 0 means no restriction
     */
    'minVip'?: number;
    /**
     * Maximum VIP level requirement (0-16), 0 means no restriction
     */
    'maxVip'?: number;
    /**
     * Product status: 1 for unlisted, 2 for listed, 3 for delisted
     */
    'status'?: number;
    /**
     * Created time
     */
    'createTime'?: string;
    /**
     * User maximum earn amount
     */
    'userMaxLendVolume'?: string;
    /**
     * Total amount the user has invested in earn products
     */
    'userTotalAmount'?: string;
    /**
     * Sale status: 1 for on sale, 2 for sold out
     */
    'saleStatus'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'asset',
            baseName: 'asset',
            type: 'string',
        },
        {
            name: 'lockUpPeriod',
            baseName: 'lock_up_period',
            type: 'number',
        },
        {
            name: 'minLendAmount',
            baseName: 'min_lend_amount',
            type: 'string',
        },
        {
            name: 'userMaxLendAmount',
            baseName: 'user_max_lend_amount',
            type: 'string',
        },
        {
            name: 'totalLendAmount',
            baseName: 'total_lend_amount',
            type: 'string',
        },
        {
            name: 'yearRate',
            baseName: 'year_rate',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'number',
        },
        {
            name: 'preRedeem',
            baseName: 'pre_redeem',
            type: 'number',
        },
        {
            name: 'reinvest',
            baseName: 'reinvest',
            type: 'number',
        },
        {
            name: 'redeemAccount',
            baseName: 'redeem_account',
            type: 'number',
        },
        {
            name: 'minVip',
            baseName: 'min_vip',
            type: 'number',
        },
        {
            name: 'maxVip',
            baseName: 'max_vip',
            type: 'number',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'number',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'string',
        },
        {
            name: 'userMaxLendVolume',
            baseName: 'user_max_lend_volume',
            type: 'string',
        },
        {
            name: 'userTotalAmount',
            baseName: 'user_total_amount',
            type: 'string',
        },
        {
            name: 'saleStatus',
            baseName: 'sale_status',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return FixedTermProduct.attributeTypeMap;
    }
}
