/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class FlashSwapMultiCurrencyPreviewParam {
    /**
     * Currency to sell
     */
    'sellAsset': string;
    /**
     * Sell amount
     */
    'sellAmount'?: string;
    /**
     * Currency to buy
     */
    'buyAsset': string;
    /**
     * Buy amount
     */
    'buyAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'sellAsset',
            baseName: 'sell_asset',
            type: 'string',
        },
        {
            name: 'sellAmount',
            baseName: 'sell_amount',
            type: 'string',
        },
        {
            name: 'buyAsset',
            baseName: 'buy_asset',
            type: 'string',
        },
        {
            name: 'buyAmount',
            baseName: 'buy_amount',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return FlashSwapMultiCurrencyPreviewParam.attributeTypeMap;
    }
}
