/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Statistical data
 */
export class FuturesAccountHistory {
    /**
     * total amount of deposit and withdraw
     */
    'dnw'?: string;
    /**
     * total amount of trading profit and loss
     */
    'pnl'?: string;
    /**
     * total amount of fee
     */
    'fee'?: string;
    /**
     * total amount of referrer rebates
     */
    'refr'?: string;
    /**
     * total amount of funding costs
     */
    'fund'?: string;
    /**
     * total amount of point deposit and withdraw
     */
    'pointDnw'?: string;
    /**
     * total amount of point fee
     */
    'pointFee'?: string;
    /**
     * total amount of referrer rebates of point fee
     */
    'pointRefr'?: string;
    /**
     * total amount of perpetual contract bonus transfer
     */
    'bonusDnw'?: string;
    /**
     * total amount of perpetual contract bonus deduction
     */
    'bonusOffset'?: string;
    /**
     * Represents the value of profit settlement from the futures account to the spot account under Unified Account Mode. Negative values indicate settlement from futures to spot, while positive values indicate settlement from spot to futures. This value is cumulative.
     */
    'crossSettle'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'dnw',
            baseName: 'dnw',
            type: 'string',
        },
        {
            name: 'pnl',
            baseName: 'pnl',
            type: 'string',
        },
        {
            name: 'fee',
            baseName: 'fee',
            type: 'string',
        },
        {
            name: 'refr',
            baseName: 'refr',
            type: 'string',
        },
        {
            name: 'fund',
            baseName: 'fund',
            type: 'string',
        },
        {
            name: 'pointDnw',
            baseName: 'point_dnw',
            type: 'string',
        },
        {
            name: 'pointFee',
            baseName: 'point_fee',
            type: 'string',
        },
        {
            name: 'pointRefr',
            baseName: 'point_refr',
            type: 'string',
        },
        {
            name: 'bonusDnw',
            baseName: 'bonus_dnw',
            type: 'string',
        },
        {
            name: 'bonusOffset',
            baseName: 'bonus_offset',
            type: 'string',
        },
        {
            name: 'crossSettle',
            baseName: 'cross_settle',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return FuturesAccountHistory.attributeTypeMap;
    }
}
