/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * contractBBOorderdetails
 */
export class FuturesBBOOrder {
    /**
     * Futures contract
     */
    'contract': string;
    /**
     * Required. Trading quantity. Positive for buy, negative for sell. Set to 0 for close position orders.
     */
    'size': number;
    /**
     * Direction: \'sell\' fetches the bid side, \'buy\' fetches the ask side.
     */
    'direction': string;
    /**
     * Display size for iceberg orders. 0 for non-iceberg orders. Note that hidden portions are charged taker fees.
     */
    'iceberg'?: number;
    /**
     * Level: maximum 20 levels
     */
    'level': number;
    /**
     * Set as `true` to close the position, with `size` set to 0
     */
    'close'?: boolean;
    /**
     * Is the order to close position
     */
    'isClose'?: boolean;
    /**
     * Set as `true` to be reduce-only order
     */
    'reduceOnly'?: boolean;
    /**
     * Is the order reduce-only
     */
    'isReduceOnly'?: boolean;
    /**
     * Is the order for liquidation
     */
    'isLiq'?: boolean;
    /**
     * Time in force  - gtc: GoodTillCancelled - ioc: ImmediateOrCancelled, taker only - poc: PendingOrCancelled, makes a post-only order that always enjoys a maker fee - fok: FillOrKill, fill either completely or none
     */
    'tif'?: FuturesBBOOrder.Tif;
    /**
     * Unfilled quantity
     */
    'left'?: number;
    /**
     * Fill price
     */
    'fillPrice'?: string;
    /**
     * 订单自定义信息，用户可以用该字段设置自定义 ID，用户自定义字段必须满足以下条件：  1. 必须以 `t-` 开头 2. 不计算 `t-` ，长度不能超过 28 字节 3. 输入内容只能包含数字、字母、下划线(_)、中划线(-) 或者点(.)  除用户自定义信息以外，以下为内部保留字段，标识订单来源:  - web: 网页 - api: API 调用 - app: 移动端 - auto_deleveraging: 自动减仓 - liquidation: ⽼经典模式仓位强制平仓 - liq-xxx: a. 新经典模式仓位强制平仓，包含逐仓、单向全仓、双向全仓⾮对冲仓位强平。 b. 统⼀账户单币种保证金模式逐仓强制平仓 - hedge-liq-xxx: 新经典模式双向全仓对冲部分强制平仓，即同时平多空仓位 - pm_liquidate: 统⼀账户跨币种保证金模式强制平仓 - comb_margin_liquidate: 统⼀账户组合保证金模式强制平仓 - scm_liquidate: 统⼀账户单币种保证金模式仓位强制平仓 - insurance: 保险
     */
    'text'?: string;
    /**
     * Taker fee
     */
    'tkfr'?: string;
    /**
     * Maker fee
     */
    'mkfr'?: string;
    /**
     * Referrer user ID
     */
    'refu'?: number;
    /**
     * Set side to close dual-mode position. `close_long` closes the long side; while `close_short` the short one. Note `size` also needs to be set to 0
     */
    'autoSize'?: FuturesBBOOrder.AutoSize;
    /**
     * Orders between users in the same `stp_id` group are not allowed to be self-traded  1. If the `stp_id` of two orders being matched is non-zero and equal, they will not be executed. Instead, the corresponding strategy will be executed based on the `stp_act` of the taker. 2. `stp_id` returns `0` by default for orders that have not been set for `STP group`
     */
    'stpId'?: number;
    /**
     * Self-Trading Prevention Action. Users can use this field to set self-trade prevention strategies  1. After users join the `STP Group`, they can pass `stp_act` to limit the user\'s self-trade prevention strategy. If `stp_act` is not passed, the default is `cn` strategy. 2. When the user does not join the `STP group`, an error will be returned when passing the `stp_act` parameter. 3. If the user did not use `stp_act` when placing the order, `stp_act` will return \'-\'  - cn: Cancel newest, cancel new orders and keep old ones - co: Cancel oldest, cancel old orders and keep new ones - cb: Cancel both, both old and new orders will be cancelled
     */
    'stpAct'?: FuturesBBOOrder.StpAct;
    /**
     * The custom data that the user remarked when amending the order
     */
    'amendText'?: string;
    /**
     * Counterparty user\'s VIP level for limit order fills. Current order will only match with orders whose VIP level is less than or equal to the specified level. Only 11~16 are supported; default is 0
     */
    'limitVip'?: number;
    /**
     * Position ID
     */
    'pid'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'contract',
            baseName: 'contract',
            type: 'string',
        },
        {
            name: 'size',
            baseName: 'size',
            type: 'number',
        },
        {
            name: 'direction',
            baseName: 'direction',
            type: 'string',
        },
        {
            name: 'iceberg',
            baseName: 'iceberg',
            type: 'number',
        },
        {
            name: 'level',
            baseName: 'level',
            type: 'number',
        },
        {
            name: 'close',
            baseName: 'close',
            type: 'boolean',
        },
        {
            name: 'isClose',
            baseName: 'is_close',
            type: 'boolean',
        },
        {
            name: 'reduceOnly',
            baseName: 'reduce_only',
            type: 'boolean',
        },
        {
            name: 'isReduceOnly',
            baseName: 'is_reduce_only',
            type: 'boolean',
        },
        {
            name: 'isLiq',
            baseName: 'is_liq',
            type: 'boolean',
        },
        {
            name: 'tif',
            baseName: 'tif',
            type: 'FuturesBBOOrder.Tif',
        },
        {
            name: 'left',
            baseName: 'left',
            type: 'number',
        },
        {
            name: 'fillPrice',
            baseName: 'fill_price',
            type: 'string',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
        {
            name: 'tkfr',
            baseName: 'tkfr',
            type: 'string',
        },
        {
            name: 'mkfr',
            baseName: 'mkfr',
            type: 'string',
        },
        {
            name: 'refu',
            baseName: 'refu',
            type: 'number',
        },
        {
            name: 'autoSize',
            baseName: 'auto_size',
            type: 'FuturesBBOOrder.AutoSize',
        },
        {
            name: 'stpId',
            baseName: 'stp_id',
            type: 'number',
        },
        {
            name: 'stpAct',
            baseName: 'stp_act',
            type: 'FuturesBBOOrder.StpAct',
        },
        {
            name: 'amendText',
            baseName: 'amend_text',
            type: 'string',
        },
        {
            name: 'limitVip',
            baseName: 'limit_vip',
            type: 'number',
        },
        {
            name: 'pid',
            baseName: 'pid',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return FuturesBBOOrder.attributeTypeMap;
    }
}

export namespace FuturesBBOOrder {
    export enum Tif {
        Gtc = <any>'gtc',
        Ioc = <any>'ioc',
        Poc = <any>'poc',
        Fok = <any>'fok',
    }
    export enum AutoSize {
        Long = <any>'close_long',
        Short = <any>'close_short',
    }
    export enum StpAct {
        Co = <any>'co',
        Cn = <any>'cn',
        Cb = <any>'cb',
        Minus = <any>'-',
    }
}
