/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Modify Price Order Details
 */
export class FuturesUpdatePriceTriggeredOrder {
    /**
     * Settlement Currency (e.g., USDT, BTC)
     */
    'settle'?: string;
    /**
     * ID of the Pending Take-Profit/Stop-Loss Trigger Order
     */
    'orderId'?: number;
    /**
     * The order ID of the modified price-triggered order. This ID is returned upon successful creation of the price-triggered order. Note: This ID must be passed in both the request path and request body.
     */
    'contact'?: string;
    /**
     * Modified Contract Quantity. Full Close: 0; Partial Close: Positive/Negative values indicate direction (consistent with the creation interface logic).
     */
    'size'?: number;
    /**
     * Represents the modified trading price. A value of 0 indicates a market order.
     */
    'price'?: string;
    /**
     * Modified Trigger Price
     */
    'triggerPrice'?: string;
    /**
     * Reference price type. 0 - Latest trade price, 1 - Mark price, 2 - Index price
     */
    'priceType'?: FuturesUpdatePriceTriggeredOrder.PriceType;
    /**
     * One-way Mode: auto_size is not required Hedge Mode partial closing (size≠0): auto_size is not required Hedge Mode full closing (size=0): auto_size must be set, close_long for closing long positions, close_short for closing short positions
     */
    'autoSize'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'settle',
            baseName: 'settle',
            type: 'string',
        },
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'number',
        },
        {
            name: 'contact',
            baseName: 'contact',
            type: 'string',
        },
        {
            name: 'size',
            baseName: 'size',
            type: 'number',
        },
        {
            name: 'price',
            baseName: 'price',
            type: 'string',
        },
        {
            name: 'triggerPrice',
            baseName: 'trigger_price',
            type: 'string',
        },
        {
            name: 'priceType',
            baseName: 'price_type',
            type: 'FuturesUpdatePriceTriggeredOrder.PriceType',
        },
        {
            name: 'autoSize',
            baseName: 'auto_size',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return FuturesUpdatePriceTriggeredOrder.attributeTypeMap;
    }
}

export namespace FuturesUpdatePriceTriggeredOrder {
    export enum PriceType {
        NUMBER_0 = <any>0,
        NUMBER_1 = <any>1,
        NUMBER_2 = <any>2,
    }
}
