/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Get chat history request
 */
export class GetChatsListRequest {
    /**
     * Order ID; omit or `0` to return the latest order with chat for the user.
     */
    'txid'?: number;
    /**
     * Timestamp of the last received message for backward incremental fetch; omit on first load.
     */
    'lastreceived'?: number;
    /**
     * Timestamp of first received message for paging backward; omit on first load.
     */
    'firstreceived'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'txid',
            baseName: 'txid',
            type: 'number',
        },
        {
            name: 'lastreceived',
            baseName: 'lastreceived',
            type: 'number',
        },
        {
            name: 'firstreceived',
            baseName: 'firstreceived',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return GetChatsListRequest.attributeTypeMap;
    }
}
