/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 用户空投发放记录单项
 */
export class HodlerAirdropV4UserAirdropRecord {
    /**
     * Product ID
     */
    'hodlerId': string;
    /**
     * 空投币种
     */
    'asset': string;
    /**
     * 基础空投金额
     */
    'receiveAmountBase'?: string;
    /**
     * 额外空投金额（余币宝加成）
     */
    'receiveAmountExt'?: string;
    /**
     * 空投发放时间，格式 Y-m-d H:i:s，UTC；未发放时可能为空字符串
     */
    'deliveryTimest': string;
    /**
     * 自动兑换状态，0未兑换 1已兑换为GT
     */
    'exchange'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'hodlerId',
            baseName: 'hodler_id',
            type: 'string',
        },
        {
            name: 'asset',
            baseName: 'asset',
            type: 'string',
        },
        {
            name: 'receiveAmountBase',
            baseName: 'receive_amount_base',
            type: 'string',
        },
        {
            name: 'receiveAmountExt',
            baseName: 'receive_amount_ext',
            type: 'string',
        },
        {
            name: 'deliveryTimest',
            baseName: 'delivery_timest',
            type: 'string',
        },
        {
            name: 'exchange',
            baseName: 'exchange',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return HodlerAirdropV4UserAirdropRecord.attributeTypeMap;
    }
}
