/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * HODLer Airdrop活动列表项
 */
export class HodlerAirdropV4ProjectItem {
    /**
     * Product ID
     */
    'hodlerId': string;
    /**
     * Product Name
     */
    'name': string;
    /**
     * 空投币种
     */
    'asset': string;
    /**
     * 项目状态
     */
    'status': HodlerAirdropV4ProjectItem.Status;
    /**
     * 空投总量
     */
    'totalAmount': string;
    /**
     * 活动开始时间，格式 Y-m-d H:i:s，UTC
     */
    'openTimest': string;
    /**
     * 活动结束时间，格式 Y-m-d H:i:s，UTC
     */
    'closeTimest': string;
    /**
     * 每枚GT可获得的空投币数量，计算中时返回空字符串
     */
    'perGtRewardToken'?: string;
    /**
     * 参与人数
     */
    'userCount'?: string;
    /**
     * 个人参与GT上限
     */
    'maxQueueAmount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'hodlerId',
            baseName: 'hodler_id',
            type: 'string',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'asset',
            baseName: 'asset',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'HodlerAirdropV4ProjectItem.Status',
        },
        {
            name: 'totalAmount',
            baseName: 'total_amount',
            type: 'string',
        },
        {
            name: 'openTimest',
            baseName: 'open_timest',
            type: 'string',
        },
        {
            name: 'closeTimest',
            baseName: 'close_timest',
            type: 'string',
        },
        {
            name: 'perGtRewardToken',
            baseName: 'per_gt_reward_token',
            type: 'string',
        },
        {
            name: 'userCount',
            baseName: 'user_count',
            type: 'string',
        },
        {
            name: 'maxQueueAmount',
            baseName: 'max_queue_amount',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return HodlerAirdropV4ProjectItem.attributeTypeMap;
    }
}

export namespace HodlerAirdropV4ProjectItem {
    export enum Status {
        UNDERWAY = <any>'UNDERWAY',
        PREHEAT = <any>'PREHEAT',
        FINISH = <any>'FINISH',
    }
}
