/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Creation parameters for infinite grid strategies.
 */
export class InfiniteGridCreateParams {
    'money': string;
    /**
     * price floor
     */
    'priceFloor': string;
    /**
     * Profit per square
     */
    'profitPerGrid': string;
    'gridNum': number;
    'priceType': InfiniteGridCreateParams.PriceType;
    'triggerPrice'?: string;
    'stopProfit'?: string;
    'stopLoss'?: string;
    'profitSharingRatio'?: string;
    'isUseBase'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'money',
            baseName: 'money',
            type: 'string',
        },
        {
            name: 'priceFloor',
            baseName: 'price_floor',
            type: 'string',
        },
        {
            name: 'profitPerGrid',
            baseName: 'profit_per_grid',
            type: 'string',
        },
        {
            name: 'gridNum',
            baseName: 'grid_num',
            type: 'number',
        },
        {
            name: 'priceType',
            baseName: 'price_type',
            type: 'InfiniteGridCreateParams.PriceType',
        },
        {
            name: 'triggerPrice',
            baseName: 'trigger_price',
            type: 'string',
        },
        {
            name: 'stopProfit',
            baseName: 'stop_profit',
            type: 'string',
        },
        {
            name: 'stopLoss',
            baseName: 'stop_loss',
            type: 'string',
        },
        {
            name: 'profitSharingRatio',
            baseName: 'profit_sharing_ratio',
            type: 'string',
        },
        {
            name: 'isUseBase',
            baseName: 'is_use_base',
            type: 'boolean',
        },
    ];

    static getAttributeTypeMap() {
        return InfiniteGridCreateParams.attributeTypeMap;
    }
}

export namespace InfiniteGridCreateParams {
    export enum PriceType {
        NUMBER_0 = <any>0,
        NUMBER_1 = <any>1,
    }
}
