/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineObject16 {
    /**
     * Cryptocurrency
     */
    'asset'?: string;
    /**
     * Fiat currency
     */
    'fiatUnit'?: string;
    /**
     * Buy/Sell
     */
    'tradeType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'asset',
            baseName: 'asset',
            type: 'string',
        },
        {
            name: 'fiatUnit',
            baseName: 'fiat_unit',
            type: 'string',
        },
        {
            name: 'tradeType',
            baseName: 'trade_type',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineObject16.attributeTypeMap;
    }
}
