/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20013DataList } from './inlineResponse20013DataList';

/**
 * Activity type data
 */
export class InlineResponse20013Data {
    /**
     * Activity type list
     */
    'list': Array<InlineResponse20013DataList>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'list',
            baseName: 'list',
            type: 'Array<InlineResponse20013DataList>',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20013Data.attributeTypeMap;
    }
}
