/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Redirect Link
 */
export class InlineResponse2007DataJumpUrl {
    /**
     * Web Redirect Link
     */
    'web'?: string;
    /**
     * App Redirect Link
     */
    'app'?: string;
    /**
     * Mini Program Redirect Link (empty string for most types)
     */
    'miniApp'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'web',
            baseName: 'web',
            type: 'string',
        },
        {
            name: 'app',
            baseName: 'app',
            type: 'string',
        },
        {
            name: 'miniApp',
            baseName: 'mini_app',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse2007DataJumpUrl.attributeTypeMap;
    }
}
