/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse2006DataFiatCurrencyInfo {
    /**
     * Name
     */
    'name': string;
    /**
     * Image
     */
    'icon': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'icon',
            baseName: 'icon',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse2006DataFiatCurrencyInfo.attributeTypeMap;
    }
}
