/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2008DataItems } from './inlineResponse2008DataItems';

export class InlineResponse2008Data {
    /**
     * Total number of results
     */
    'total'?: number;
    /**
     * Search result list
     */
    'items'?: Array<InlineResponse2008DataItems>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'total',
            baseName: 'total',
            type: 'number',
        },
        {
            name: 'items',
            baseName: 'items',
            type: 'Array<InlineResponse2008DataItems>',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse2008Data.attributeTypeMap;
    }
}
