/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20028Assets } from './inlineResponse20028Assets';

export class InlineResponse20028 {
    /**
     * User ID
     */
    'userId': string;
    /**
     * Available Margin
     */
    'availableMargin': string;
    /**
     * marginbalance
     */
    'marginBalance': string;
    /**
     * Initial Margin
     */
    'initialMargin': string;
    /**
     * Maintenance margin
     */
    'maintenanceMargin': string;
    /**
     * Initial margin rate
     */
    'initialMarginRate': string;
    /**
     * Maintenance margin rate
     */
    'maintenanceMarginRate': string;
    /**
     * Contract Position Mode
     */
    'positionMode': string;
    /**
     * Account limit
     */
    'accountLimit'?: string;
    /**
     * Created time
     */
    'createTime': string;
    /**
     * Update time
     */
    'updateTime': string;
    /**
     * Account mode. CROSS_EXCHANGE: cross-exchange mode. ISOLATED_EXCHANGE: isolated exchange mode
     */
    'accountMode'?: string;
    /**
     * Exchange type. When account_mode is CROSS_EXCHANGE, this must be CROSSEX; otherwise, it represents a specific exchange
     */
    'exchangeType'?: string;
    'assets': Array<InlineResponse20028Assets>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'userId',
            baseName: 'user_id',
            type: 'string',
        },
        {
            name: 'availableMargin',
            baseName: 'available_margin',
            type: 'string',
        },
        {
            name: 'marginBalance',
            baseName: 'margin_balance',
            type: 'string',
        },
        {
            name: 'initialMargin',
            baseName: 'initial_margin',
            type: 'string',
        },
        {
            name: 'maintenanceMargin',
            baseName: 'maintenance_margin',
            type: 'string',
        },
        {
            name: 'initialMarginRate',
            baseName: 'initial_margin_rate',
            type: 'string',
        },
        {
            name: 'maintenanceMarginRate',
            baseName: 'maintenance_margin_rate',
            type: 'string',
        },
        {
            name: 'positionMode',
            baseName: 'position_mode',
            type: 'string',
        },
        {
            name: 'accountLimit',
            baseName: 'account_limit',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'string',
        },
        {
            name: 'updateTime',
            baseName: 'update_time',
            type: 'string',
        },
        {
            name: 'accountMode',
            baseName: 'account_mode',
            type: 'string',
        },
        {
            name: 'exchangeType',
            baseName: 'exchange_type',
            type: 'string',
        },
        {
            name: 'assets',
            baseName: 'assets',
            type: 'Array<InlineResponse20028Assets>',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20028.attributeTypeMap;
    }
}
