/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse2008Data } from './inlineResponse2008Data';

export class InlineResponse2008 {
    /**
     * Status code, 0 = success
     */
    'code'?: number;
    /**
     * Error identifier code. Empty string on success, machine-readable error label on error
     */
    'label'?: string;
    /**
     * Status message
     */
    'msg'?: string;
    'data'?: InlineResponse2008Data;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'label',
            baseName: 'label',
            type: 'string',
        },
        {
            name: 'msg',
            baseName: 'msg',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'InlineResponse2008Data',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse2008.attributeTypeMap;
    }
}
