/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20011Data } from './inlineResponse20011Data';

export class InlineResponse20011 {
    'timestamp': number;
    'method': string;
    'code': number;
    'message': string;
    'data': Array<InlineResponse20011Data>;
    'version': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
        {
            name: 'method',
            baseName: 'method',
            type: 'string',
        },
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'Array<InlineResponse20011Data>',
        },
        {
            name: 'version',
            baseName: 'version',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20011.attributeTypeMap;
    }
}
