/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Flash swap order information
 */
export class InlineResponse20016DataConvertInfo {
    /**
     * Flash swap target currency
     */
    'convertType': string;
    /**
     * Flash swap order status
     */
    'convertStatus': string;
    /**
     * Expected price when placing order
     */
    'preRate': string;
    /**
     * Execution price
     */
    'rate': string;
    /**
     * Expected fiat price when placing order
     */
    'preFiatRate': string;
    /**
     * Fiat price at execution
     */
    'fiatRate': string;
    /**
     * Size
     */
    'amount': string;
    /**
     * Swap Amount
     */
    'convertAmount': string;
    /**
     * Slippage calculation: slippage = (expected price when placing order - real-time price during auto swap) / expected price when placing order
     */
    'slippage': string;
    /**
     * Flash swap order display status
     */
    'status': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'convertType',
            baseName: 'convert_type',
            type: 'string',
        },
        {
            name: 'convertStatus',
            baseName: 'convert_status',
            type: 'string',
        },
        {
            name: 'preRate',
            baseName: 'pre_rate',
            type: 'string',
        },
        {
            name: 'rate',
            baseName: 'rate',
            type: 'string',
        },
        {
            name: 'preFiatRate',
            baseName: 'pre_fiat_rate',
            type: 'string',
        },
        {
            name: 'fiatRate',
            baseName: 'fiat_rate',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'convertAmount',
            baseName: 'convert_amount',
            type: 'string',
        },
        {
            name: 'slippage',
            baseName: 'slippage',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20016DataConvertInfo.attributeTypeMap;
    }
}
