/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20012DataList } from './inlineResponse20012DataList';
import { InlineResponse20012DataTransTime } from './inlineResponse20012DataTransTime';

export class InlineResponse20012Data {
    'list': Array<InlineResponse20012DataList>;
    /**
     * Countdown time
     */
    'transTime': Array<InlineResponse20012DataTransTime>;
    /**
     * Number of orders
     */
    'count': number;
    /**
     * Export count
     */
    'exportedNum': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'list',
            baseName: 'list',
            type: 'Array<InlineResponse20012DataList>',
        },
        {
            name: 'transTime',
            baseName: 'trans_time',
            type: 'Array<InlineResponse20012DataTransTime>',
        },
        {
            name: 'count',
            baseName: 'count',
            type: 'number',
        },
        {
            name: 'exportedNum',
            baseName: 'exported_num',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20012Data.attributeTypeMap;
    }
}
