/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse20038 {
    /**
     * User ID
     */
    'userId': string;
    /**
     * Trading Pair
     */
    'symbol': string;
    /**
     * Interest Deduction ID
     */
    'interestId': string;
    /**
     * Debt Source ID, can be Order ID or Position ID
     */
    'liabilityId': string;
    /**
     * Debt Quantity
     */
    'liability': string;
    /**
     * Debt Currency
     */
    'liabilityCoin': string;
    /**
     * Interest
     */
    'interest': string;
    /**
     * interest rate
     */
    'interestRate': string;
    /**
     * Interest deduction type (`PERIODIC_POSITION`: periodic position interest; `PERIODIC_OPEN_ORDER`: periodic open-order interest; `IMMEDIATE_OPEN_ORDER`: interest charged on order opening)
     */
    'interestType': string;
    /**
     * Created time
     */
    'createTime': string;
    /**
     * Exchange
     */
    'exchangeType': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'userId',
            baseName: 'userId',
            type: 'string',
        },
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'interestId',
            baseName: 'interest_id',
            type: 'string',
        },
        {
            name: 'liabilityId',
            baseName: 'liability_id',
            type: 'string',
        },
        {
            name: 'liability',
            baseName: 'liability',
            type: 'string',
        },
        {
            name: 'liabilityCoin',
            baseName: 'liability_coin',
            type: 'string',
        },
        {
            name: 'interest',
            baseName: 'interest',
            type: 'string',
        },
        {
            name: 'interestRate',
            baseName: 'interest_rate',
            type: 'string',
        },
        {
            name: 'interestType',
            baseName: 'interest_type',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'string',
        },
        {
            name: 'exchangeType',
            baseName: 'exchange_type',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20038.attributeTypeMap;
    }
}
