/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Place order request parameters
 */
export class InlineObject2 {
    /**
     * Order price
     */
    'price': string;
    /**
     * Price type (trigger=trigger price, market=market price)
     */
    'priceType': InlineObject2.PriceType;
    /**
     * Order side (1=sell, 2=buy)
     */
    'side': InlineObject2.Side;
    /**
     * Trading symbol code
     */
    'symbol': string;
    /**
     * Order volume
     */
    'volume': string;
    /**
     * Take profit price (optional)
     */
    'priceTp'?: string;
    /**
     * Stop loss price (optional)
     */
    'priceSl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'price',
            baseName: 'price',
            type: 'string',
        },
        {
            name: 'priceType',
            baseName: 'price_type',
            type: 'InlineObject2.PriceType',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'InlineObject2.Side',
        },
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'volume',
            baseName: 'volume',
            type: 'string',
        },
        {
            name: 'priceTp',
            baseName: 'price_tp',
            type: 'string',
        },
        {
            name: 'priceSl',
            baseName: 'price_sl',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineObject2.attributeTypeMap;
    }
}

export namespace InlineObject2 {
    export enum PriceType {
        Trigger = <any>'trigger',
        Market = <any>'market',
    }
    export enum Side {
        NUMBER_1 = <any>1,
        NUMBER_2 = <any>2,
    }
}
