/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineObject18 {
    /**
     * Order ID
     */
    'txid': number;
    /**
     * 0=Text, 1=File (video or image), default is 0 if not provided
     */
    'type'?: number;
    /**
     * Message content
     */
    'message': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'txid',
            baseName: 'txid',
            type: 'number',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineObject18.attributeTypeMap;
    }
}
