/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse20034 {
    /**
     * User ID
     */
    'userId': string;
    /**
     * Currency pair
     */
    'symbol': string;
    /**
     * CROSSEX position-reduction indicator ranking (1–5, higher value ranks higher)
     */
    'crossexAdlRank': string;
    /**
     * Original exchange information (Binance: 0–4, higher value ranks higher; OKX: 0–5, higher value ranks higher; Gate: 1–5, lower value ranks higher)
     */
    'exchangeAdlRank': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'userId',
            baseName: 'user_id',
            type: 'string',
        },
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'crossexAdlRank',
            baseName: 'crossex_adl_rank',
            type: 'string',
        },
        {
            name: 'exchangeAdlRank',
            baseName: 'exchange_adl_rank',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20034.attributeTypeMap;
    }
}
