/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CrossexRuleRiskLimitsTiers } from './crossexRuleRiskLimitsTiers';

export class InlineResponse20027 {
    'symbol'?: string;
    'tiers'?: Array<CrossexRuleRiskLimitsTiers>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'tiers',
            baseName: 'tiers',
            type: 'Array<CrossexRuleRiskLimitsTiers>',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20027.attributeTypeMap;
    }
}
