/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FixedTermHistoryRecord } from './fixedTermHistoryRecord';

export class InlineResponse2005Data {
    'list'?: Array<FixedTermHistoryRecord>;
    /**
     * Total Records
     */
    'total'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'list',
            baseName: 'list',
            type: 'Array<FixedTermHistoryRecord>',
        },
        {
            name: 'total',
            baseName: 'total',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse2005Data.attributeTypeMap;
    }
}
