/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse20020DataLists {
    /**
     * Ad buy/sell direction
     */
    'type'?: string;
    /**
     * Price
     */
    'rate'?: string;
    /**
     * Original price
     */
    'originalRate'?: string;
    /**
     * Remaining cryptocurrency amount of ad
     */
    'amount'?: string;
    /**
     * Remaining fiat amount of ad
     */
    'total'?: string;
    /**
     * Single order limit range (cryptocurrency)
     */
    'limitTotal'?: string;
    /**
     * Single order limit range (fiat)
     */
    'limitFiat'?: string;
    /**
     * Minimum quantity per order
     */
    'minAmount'?: string;
    /**
     * Maximum quantity per order
     */
    'maxAmount'?: string;
    /**
     * Payment method ID list
     */
    'payTypeNum'?: string;
    /**
     * Payment method configuration details
     */
    'payTypeJson'?: string;
    /**
     * Ad expiration time (minutes)
     */
    'expireMin'?: string;
    /**
     * VIP limit
     */
    'tierLimit'?: string;
    /**
     * Whether merchant trading restriction is allowed
     */
    'advertisersLimit'?: number;
    /**
     * Registration time limit
     */
    'regTimeLimit'?: number;
    /**
     * KYC level limit
     */
    'verifiedLimit'?: number;
    /**
     * Minimum limit of completed orders by counterparty
     */
    'minCompletedLimit'?: number;
    /**
     * Maximum limit of completed orders by counterparty
     */
    'maxCompletedLimit'?: number;
    /**
     * KYC nationality restriction
     */
    'userCountryLimit'?: number;
    /**
     * 30-day completion rate limit
     */
    'completedRateLimit'?: number;
    /**
     * Maximum order limit for counterparty
     */
    'userOrdersLimit'?: number;
    /**
     * Whether to hide payment method
     */
    'hidePayment'?: string;
    /**
     * Digital currency
     */
    'currencyType'?: string;
    /**
     * Fiat currency
     */
    'wantType'?: string;
    /**
     * Trading terms
     */
    'tradeTips'?: string;
    /**
     * Special ad type
     */
    'newHand'?: number;
    /**
     * Ad ID
     */
    'id'?: string;
    /**
     * Ad status
     */
    'status'?: string;
    /**
     * Ad frozen amount
     */
    'lockedAmount'?: string;
    /**
     * Hidden price
     */
    'hideRate'?: string;
    /**
     * Whether ad is currently expired
     */
    'isOutTime'?: number;
    /**
     * Floating price reference configuration
     */
    'rateRefId'?: number;
    /**
     * Floating ratio
     */
    'rateOffset'?: string;
    /**
     * Reference price type: 0=Floating, 1=Fixed
     */
    'rateFixed'?: number;
    /**
     * Floating order direction
     */
    'floatTrend'?: number;
    /**
     * Whether ad has disputed transactions
     */
    'inDispute'?: number;
    /**
     * Auto reply data
     */
    'autoReply'?: string;
    /**
     * Ad creation time
     */
    'timestamp'?: number;
    /**
     * Auto delegation
     */
    'isHedge'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'rate',
            baseName: 'rate',
            type: 'string',
        },
        {
            name: 'originalRate',
            baseName: 'original_rate',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'total',
            baseName: 'total',
            type: 'string',
        },
        {
            name: 'limitTotal',
            baseName: 'limit_total',
            type: 'string',
        },
        {
            name: 'limitFiat',
            baseName: 'limit_fiat',
            type: 'string',
        },
        {
            name: 'minAmount',
            baseName: 'min_amount',
            type: 'string',
        },
        {
            name: 'maxAmount',
            baseName: 'max_amount',
            type: 'string',
        },
        {
            name: 'payTypeNum',
            baseName: 'pay_type_num',
            type: 'string',
        },
        {
            name: 'payTypeJson',
            baseName: 'pay_type_json',
            type: 'string',
        },
        {
            name: 'expireMin',
            baseName: 'expire_min',
            type: 'string',
        },
        {
            name: 'tierLimit',
            baseName: 'tier_limit',
            type: 'string',
        },
        {
            name: 'advertisersLimit',
            baseName: 'advertisers_limit',
            type: 'number',
        },
        {
            name: 'regTimeLimit',
            baseName: 'reg_time_limit',
            type: 'number',
        },
        {
            name: 'verifiedLimit',
            baseName: 'verified_limit',
            type: 'number',
        },
        {
            name: 'minCompletedLimit',
            baseName: 'min_completed_limit',
            type: 'number',
        },
        {
            name: 'maxCompletedLimit',
            baseName: 'max_completed_limit',
            type: 'number',
        },
        {
            name: 'userCountryLimit',
            baseName: 'user_country_limit',
            type: 'number',
        },
        {
            name: 'completedRateLimit',
            baseName: 'completed_rate_limit',
            type: 'number',
        },
        {
            name: 'userOrdersLimit',
            baseName: 'user_orders_limit',
            type: 'number',
        },
        {
            name: 'hidePayment',
            baseName: 'hide_payment',
            type: 'string',
        },
        {
            name: 'currencyType',
            baseName: 'currencyType',
            type: 'string',
        },
        {
            name: 'wantType',
            baseName: 'want_type',
            type: 'string',
        },
        {
            name: 'tradeTips',
            baseName: 'trade_tips',
            type: 'string',
        },
        {
            name: 'newHand',
            baseName: 'new_hand',
            type: 'number',
        },
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'lockedAmount',
            baseName: 'locked_amount',
            type: 'string',
        },
        {
            name: 'hideRate',
            baseName: 'hide_rate',
            type: 'string',
        },
        {
            name: 'isOutTime',
            baseName: 'is_out_time',
            type: 'number',
        },
        {
            name: 'rateRefId',
            baseName: 'rate_ref_id',
            type: 'number',
        },
        {
            name: 'rateOffset',
            baseName: 'rate_offset',
            type: 'string',
        },
        {
            name: 'rateFixed',
            baseName: 'rate_fixed',
            type: 'number',
        },
        {
            name: 'floatTrend',
            baseName: 'float_trend',
            type: 'number',
        },
        {
            name: 'inDispute',
            baseName: 'in_dispute',
            type: 'number',
        },
        {
            name: 'autoReply',
            baseName: 'auto_reply',
            type: 'string',
        },
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
        {
            name: 'isHedge',
            baseName: 'is_hedge',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20020DataLists.attributeTypeMap;
    }
}
