/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class InlineResponse20035SpecialFeeList {
    /**
     * Currency pair
     */
    'symbol': string;
    /**
     * Taker fee rate
     */
    'takerFeeRate': string;
    /**
     * Maker fee rate
     */
    'makerFeeRate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'takerFeeRate',
            baseName: 'taker_fee_rate',
            type: 'string',
        },
        {
            name: 'makerFeeRate',
            baseName: 'maker_fee_rate',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20035SpecialFeeList.attributeTypeMap;
    }
}
