/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse20013Data } from './inlineResponse20013Data';

export class InlineResponse20013 {
    /**
     * Response status code, 0 means success
     */
    'code': number;
    /**
     * 响应消息，成功时为 \"success\"
     */
    'message': string;
    'data': InlineResponse20013Data;
    /**
     * Server timestamp (milliseconds)
     */
    'timestamp': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'InlineResponse20013Data',
        },
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return InlineResponse20013.attributeTypeMap;
    }
}
