/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class KeyPerms {
    /**
     * 权限功能名称（不传值即为清空）  - `wallet`: 钱包 - `spot`: 现货/杠杆 - `futures`: 永续合约 - `delivery`: 交割合约 - `earn`: 理财 - `custody`: 托管 - `options`: 期权 - `account`: 账户信息 - `loan`: 借贷 - `margin`: 杠杆 - `unified`: 统一账户 - `copy`: 跟单 - `pilot`: 创新 - `otc`: otc - `alpha`: alpha - `crossx`: 跨所
     */
    'name'?: string;
    /**
     * Read Only
     */
    'readOnly'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'readOnly',
            baseName: 'read_only',
            type: 'boolean',
        },
    ];

    static getAttributeTypeMap() {
        return KeyPerms.attributeTypeMap;
    }
}
