/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LaunchPoolV4RewardPool } from './launchPoolV4RewardPool';

export class LaunchPoolV4Project {
    /**
     * Product ID
     */
    'pid': number;
    /**
     * Product Name
     */
    'name': string;
    /**
     * Total rewards
     */
    'totalAmount': string;
    /**
     * Project start timestamp
     */
    'startTimest': number;
    /**
     * Project end timestamp
     */
    'endTimest': number;
    /**
     * Staking period (in days)
     */
    'days': number;
    /**
     * Project status: 1 for ongoing, 2 for warming up, 3 for ended
     */
    'projectState': LaunchPoolV4Project.ProjectState;
    /**
     * Collateral currency list
     */
    'rewardPools': Array<LaunchPoolV4RewardPool>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'pid',
            baseName: 'pid',
            type: 'number',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'totalAmount',
            baseName: 'total_amount',
            type: 'string',
        },
        {
            name: 'startTimest',
            baseName: 'start_timest',
            type: 'number',
        },
        {
            name: 'endTimest',
            baseName: 'end_timest',
            type: 'number',
        },
        {
            name: 'days',
            baseName: 'days',
            type: 'number',
        },
        {
            name: 'projectState',
            baseName: 'project_state',
            type: 'LaunchPoolV4Project.ProjectState',
        },
        {
            name: 'rewardPools',
            baseName: 'reward_pools',
            type: 'Array<LaunchPoolV4RewardPool>',
        },
    ];

    static getAttributeTypeMap() {
        return LaunchPoolV4Project.attributeTypeMap;
    }
}

export namespace LaunchPoolV4Project {
    export enum ProjectState {
        NUMBER_1 = <any>1,
        NUMBER_2 = <any>2,
        NUMBER_3 = <any>3,
    }
}
