/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListUserCouponsResponseDataHelpUrl } from './listUserCouponsResponseDataHelpUrl';
import { ListUserCouponsResponseDataJumpUrl } from './listUserCouponsResponseDataJumpUrl';
import { ListUserCouponsResponseDataProgressConfig } from './listUserCouponsResponseDataProgressConfig';

export class ListUserCouponsResponseDataList {
    /**
     * Coupon distribution record ID (coupon_send_issuing_log.id), used as `last_id` for cursor-based pagination
     */
    'id'?: number;
    /**
     * User coupon detail table primary key (separate table per type). This field is 0 for task coupons, has value for regular coupons
     */
    'detailsId'?: number;
    /**
     * Coupon type, enum values same as the `type` parameter
     */
    'couponType'?: string;
    /**
     * Coupon display name (i18n translated)
     */
    'name'?: string;
    /**
     * Coupon denomination (formatted string with thousand separators). Meaning by type: point card = balance, interest rate boost coupon = interest rate percentage (e.g., \'5%\'), VIP trial card = VIP level number, position voucher = face value × leverage, others = face value
     */
    'amount'?: string;
    /**
     * Original denomination (string with trailing zeros removed). Only returned for point card type, other types do not have this field
     */
    'originAmount'?: string;
    /**
     * Denomination unit. Point card = \'POINT\', interest rate boost coupon = \'APR\', VIP trial card = \'VIP\', Alpha cash coupon = base currency, others = uppercase currency symbol (e.g., \'USDT\'/\'GT\')
     */
    'currency'?: string;
    /**
     * Coupon usage rule text. List endpoint always returns empty string \"\", only detail endpoint returns actual value
     */
    'ruleNew'?: string;
    /**
     * Coupon status. Regular coupon: NOT_ACTIVE (pending activation), ACTIVATED (activated), TO_BE_USED (to be used), EXPIRED (expired), RECYCLED (recycled), INVALID (invalidated), USED (used), UNKNOWN (unknown), LOCKED (locked, P2P only). Task coupon: TASK_START (task not started), TASK_WAIT (task in progress), TASK_DONE (task completed, processing), TASK_EXPIRED (task not completed, expired), TASK_NOT_STARTED_EXPIRED (not started, expired), TASK_RECEIVE_SUCCESS (reward claimed successfully), TASK_RECEIVE_FAIL (reward claim failed)
     */
    'status'?: ListUserCouponsResponseDataList.Status;
    'jumpUrl'?: ListUserCouponsResponseDataJumpUrl;
    'helpUrl'?: ListUserCouponsResponseDataHelpUrl;
    /**
     * Expiration time (Unix timestamp). Some types replace this with actual expiration time after activation or use (e.g., contract_bonus uses expired_timest after activation). Point card type returns 0
     */
    'expireTime'?: number;
    /**
     * Sorting expiration time (from the original expiration time of the distribution record, unaffected by activation). Used as the `expire_time` parameter for the next request in cursor-based pagination
     */
    'expireTimeOrderBy'?: number;
    /**
     * Seconds remaining until expiration. Returns 0 for expired or Point Card types
     */
    'expireSecond'?: number;
    /**
     * Whether there is a usage history. Fixed as true for point card type, determined by type for others
     */
    'hasUsageHistory'?: boolean;
    /**
     * Whether to display a progress bar. Only true for commission_rebate, interest_voucher, and qualifying task coupons
     */
    'hasProgress'?: boolean;
    'progressConfig'?: ListUserCouponsResponseDataProgressConfig;
    /**
     * Type-specific activation information. Types without specific fields return empty object {}. Fields by type: interest_voucher={supported_pairs,transaction_type}; contract_bonus_new={received_expired_hour}; contract_bonus={check_unified_account_mode,received_expired_days,abtest}; commission_rebate={market,market_name}; robot_bonus={designated_bots}; position_voucher={symbols,leverage,need_user_funds,user_funds_amount,position_bonus}; tradfi_position_voucher={symbols,leverage,position_bonus}; etf_voucher={currency_markets,amount}
     */
    'activationInfo'?: object;
    /**
     * Whether it is a task coupon. `0` = regular coupon; `1` = task coupon
     */
    'isTaskCoupon'?: ListUserCouponsResponseDataList.IsTaskCoupon;
    /**
     * Whether to prompt the user to upgrade the App (true when app version is too old to support the coupon). Triggered types: copy_trading/alpha_voucher (Android<7320000/iOS<202507320000), commission_rebate subtype tradfi (Android<8040000/iOS<202608040000), etf_voucher (Android<8090000/iOS<202608090000), tradfi_position_voucher (Android<8100000/iOS<202508240000)
     */
    'upgradeToast'?: boolean;
    /**
     * Task title (only task coupons have value, regular coupons return empty string \"\")
     */
    'taskTitle'?: string;
    /**
     * Task description (only task coupons have value, regular coupons return empty string \"\")
     */
    'taskDesc'?: string;
    /**
     * Task start timestamp (Unix). Only has value for task coupons in TASK_EXPIRED status, otherwise 0
     */
    'taskStartAt'?: number;
    /**
     * Task expiration timestamp (Unix). Currently fixed at 0, reserved field
     */
    'taskExpireAt'?: number;
    /**
     * Task completion timestamp (Unix). Currently fixed at 0, reserved field
     */
    'taskCompletedAt'?: number;
    /**
     * Extension fields. List endpoint always returns empty array [], only the detail endpoint has values
     */
    'extra'?: Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'number',
        },
        {
            name: 'detailsId',
            baseName: 'details_id',
            type: 'number',
        },
        {
            name: 'couponType',
            baseName: 'coupon_type',
            type: 'string',
        },
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'originAmount',
            baseName: 'origin_amount',
            type: 'string',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'ruleNew',
            baseName: 'rule_new',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'ListUserCouponsResponseDataList.Status',
        },
        {
            name: 'jumpUrl',
            baseName: 'jump_url',
            type: 'ListUserCouponsResponseDataJumpUrl',
        },
        {
            name: 'helpUrl',
            baseName: 'help_url',
            type: 'ListUserCouponsResponseDataHelpUrl',
        },
        {
            name: 'expireTime',
            baseName: 'expire_time',
            type: 'number',
        },
        {
            name: 'expireTimeOrderBy',
            baseName: 'expire_time_order_by',
            type: 'number',
        },
        {
            name: 'expireSecond',
            baseName: 'expire_second',
            type: 'number',
        },
        {
            name: 'hasUsageHistory',
            baseName: 'has_usage_history',
            type: 'boolean',
        },
        {
            name: 'hasProgress',
            baseName: 'has_progress',
            type: 'boolean',
        },
        {
            name: 'progressConfig',
            baseName: 'progress_config',
            type: 'ListUserCouponsResponseDataProgressConfig',
        },
        {
            name: 'activationInfo',
            baseName: 'activation_info',
            type: 'object',
        },
        {
            name: 'isTaskCoupon',
            baseName: 'is_task_coupon',
            type: 'ListUserCouponsResponseDataList.IsTaskCoupon',
        },
        {
            name: 'upgradeToast',
            baseName: 'upgrade_toast',
            type: 'boolean',
        },
        {
            name: 'taskTitle',
            baseName: 'task_title',
            type: 'string',
        },
        {
            name: 'taskDesc',
            baseName: 'task_desc',
            type: 'string',
        },
        {
            name: 'taskStartAt',
            baseName: 'task_start_at',
            type: 'number',
        },
        {
            name: 'taskExpireAt',
            baseName: 'task_expire_at',
            type: 'number',
        },
        {
            name: 'taskCompletedAt',
            baseName: 'task_completed_at',
            type: 'number',
        },
        {
            name: 'extra',
            baseName: 'extra',
            type: 'Array<object>',
        },
    ];

    static getAttributeTypeMap() {
        return ListUserCouponsResponseDataList.attributeTypeMap;
    }
}

export namespace ListUserCouponsResponseDataList {
    export enum Status {
        NOTACTIVE = <any>'NOT_ACTIVE',
        ACTIVATED = <any>'ACTIVATED',
        TOBEUSED = <any>'TO_BE_USED',
        EXPIRED = <any>'EXPIRED',
        RECYCLED = <any>'RECYCLED',
        INVALID = <any>'INVALID',
        USED = <any>'USED',
        UNKNOWN = <any>'UNKNOWN',
        LOCKED = <any>'LOCKED',
        TASKSTART = <any>'TASK_START',
        TASKWAIT = <any>'TASK_WAIT',
        TASKDONE = <any>'TASK_DONE',
        TASKEXPIRED = <any>'TASK_EXPIRED',
        TASKNOTSTARTEDEXPIRED = <any>'TASK_NOT_STARTED_EXPIRED',
        TASKRECEIVESUCCESS = <any>'TASK_RECEIVE_SUCCESS',
        TASKRECEIVEFAIL = <any>'TASK_RECEIVE_FAIL',
    }
    export enum IsTaskCoupon {
        NUMBER_0 = <any>0,
        NUMBER_1 = <any>1,
    }
}
