/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Order response
 */
export class OrderResponse {
    /**
     * Order ID
     */
    'orderId'?: string;
    /**
     * Transaction Hash
     */
    'txHash'?: string;
    /**
     * Buy or sell orders - buy - sell
     */
    'side'?: string;
    /**
     * Amount (USDT)
     */
    'usdtAmount'?: string;
    /**
     * Token
     */
    'currency'?: string;
    /**
     * Token amount
     */
    'currencyAmount'?: string;
    /**
     * Order Status - `0` : All - `1` : Processing - `2` : Successful - `3` : Failed - `4` : Cancelled - `5` : Buy order placed but transfer not completed - `6` : Order cancelled but transfer not completed
     */
    'status'?: number;
    /**
     * Trading mode affects slippage selection - `speed` : Smart mode - `custom` : Custom mode, uses `slippage` parameter
     */
    'gasMode'?: string;
    /**
     * Blockchain
     */
    'chain'?: string;
    /**
     * Gas Fee (USDT-based)
     */
    'gasFee'?: string;
    /**
     * Trading Fee (USDT-based)
     */
    'transactionFee'?: string;
    /**
     * Failure reason (if applicable)
     */
    'failedReason'?: string;
    /**
     * Creation timestamp
     */
    'createTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'string',
        },
        {
            name: 'txHash',
            baseName: 'tx_hash',
            type: 'string',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'string',
        },
        {
            name: 'usdtAmount',
            baseName: 'usdt_amount',
            type: 'string',
        },
        {
            name: 'currency',
            baseName: 'currency',
            type: 'string',
        },
        {
            name: 'currencyAmount',
            baseName: 'currency_amount',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'number',
        },
        {
            name: 'gasMode',
            baseName: 'gas_mode',
            type: 'string',
        },
        {
            name: 'chain',
            baseName: 'chain',
            type: 'string',
        },
        {
            name: 'gasFee',
            baseName: 'gas_fee',
            type: 'string',
        },
        {
            name: 'transactionFee',
            baseName: 'transaction_fee',
            type: 'string',
        },
        {
            name: 'failedReason',
            baseName: 'failed_reason',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return OrderResponse.attributeTypeMap;
    }
}
