/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Order detail
 */
export class OrderListDataList {
    /**
     * Order ID
     */
    'orderId'?: number;
    /**
     * Currency pair
     */
    'symbol'?: string;
    /**
     * Trading symbol description
     */
    'symbolDesc'?: string;
    /**
     * Trade type (market=market price, trigger=trigger price)
     */
    'priceType'?: OrderListDataList.PriceType;
    /**
     * Order status code
     */
    'state'?: number;
    /**
     * Order status description
     */
    'stateDesc'?: string;
    /**
     * Is completed (0=shown in active order list, 1=not shown in active list)
     */
    'finished'?: OrderListDataList.Finished;
    /**
     * Order side (1=sell, 2=buy)
     */
    'side'?: OrderListDataList.Side;
    /**
     * Order volume
     */
    'volume'?: string;
    /**
     * Trigger price
     */
    'price'?: string;
    /**
     * Take profit price
     */
    'priceTp'?: string;
    /**
     * Stop loss price
     */
    'priceSl'?: string;
    /**
     * Order time (Unix timestamp in seconds)
     */
    'timeSetup'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'number',
        },
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'symbolDesc',
            baseName: 'symbol_desc',
            type: 'string',
        },
        {
            name: 'priceType',
            baseName: 'price_type',
            type: 'OrderListDataList.PriceType',
        },
        {
            name: 'state',
            baseName: 'state',
            type: 'number',
        },
        {
            name: 'stateDesc',
            baseName: 'state_desc',
            type: 'string',
        },
        {
            name: 'finished',
            baseName: 'finished',
            type: 'OrderListDataList.Finished',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'OrderListDataList.Side',
        },
        {
            name: 'volume',
            baseName: 'volume',
            type: 'string',
        },
        {
            name: 'price',
            baseName: 'price',
            type: 'string',
        },
        {
            name: 'priceTp',
            baseName: 'price_tp',
            type: 'string',
        },
        {
            name: 'priceSl',
            baseName: 'price_sl',
            type: 'string',
        },
        {
            name: 'timeSetup',
            baseName: 'time_setup',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return OrderListDataList.attributeTypeMap;
    }
}

export namespace OrderListDataList {
    export enum PriceType {
        Market = <any>'market',
        Trigger = <any>'trigger',
    }
    export enum Finished {
        NUMBER_0 = <any>0,
        NUMBER_1 = <any>1,
    }
    export enum Side {
        NUMBER_1 = <any>1,
        NUMBER_2 = <any>2,
    }
}
