/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PreviewFromParam } from './previewFromParam';
import { PreviewToParam } from './previewToParam';

/**
 * 资产配置优化**预览**请求。`from` 为卖出数量；`to` 为目标币种及**分配比例 ratio**（不是绝对数量）。 正式下单请使用 `OrderCreateV1Req`，其 `to` 为 `amount`。
 */
export class OrderPreviewV1Req {
    /**
     * 卖出侧；每项为币种 + 换出数量 `amount`（字符串十进制）。
     */
    'from': Array<PreviewFromParam>;
    /**
     * 目标侧；每项为币种 + **比例** `ratio`（字符串十进制，如 `0.5`）。 典型来源：`GET /asset-swap/config` → `recommend_v2` 某分组下策略的 `schemes[].name` / `schemes[].ratio`。
     */
    'to': Array<PreviewToParam>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'from',
            baseName: 'from',
            type: 'Array<PreviewFromParam>',
        },
        {
            name: 'to',
            baseName: 'to',
            type: 'Array<PreviewToParam>',
        },
    ];

    static getAttributeTypeMap() {
        return OrderPreviewV1Req.attributeTypeMap;
    }
}
