/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Inner create-bank-card `multipart/form-data`. Use the form field `documentation_file` to upload the account-opening proof.
 */
export class OtcBankCreateMultipartRequest {
    'bankAccountName': string;
    'bankName': string;
    'bankCountry': string;
    'bankAddress': string;
    'iban': string;
    'swift': string;
    'remittanceLineNumber'?: string;
    'agentBankName'?: string;
    'agentBankSwift'?: string;
    /**
     * 开户证明文件内容（multipart 文件字段，二进制/Base64；jpg/jpeg/png/pdf 等，单文件≤4MB 以现网为准）
     */
    'documentationFile': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'bankAccountName',
            baseName: 'bank_account_name',
            type: 'string',
        },
        {
            name: 'bankName',
            baseName: 'bank_name',
            type: 'string',
        },
        {
            name: 'bankCountry',
            baseName: 'bank_country',
            type: 'string',
        },
        {
            name: 'bankAddress',
            baseName: 'bank_address',
            type: 'string',
        },
        {
            name: 'iban',
            baseName: 'iban',
            type: 'string',
        },
        {
            name: 'swift',
            baseName: 'swift',
            type: 'string',
        },
        {
            name: 'remittanceLineNumber',
            baseName: 'remittance_line_number',
            type: 'string',
        },
        {
            name: 'agentBankName',
            baseName: 'agent_bank_name',
            type: 'string',
        },
        {
            name: 'agentBankSwift',
            baseName: 'agent_bank_swift',
            type: 'string',
        },
        {
            name: 'documentationFile',
            baseName: 'documentation_file',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return OtcBankCreateMultipartRequest.attributeTypeMap;
    }
}
