/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OtcBankSupplementChecklistResponseData } from './otcBankSupplementChecklistResponseData';

export class OtcBankSupplementChecklistResponse {
    'code': number;
    'message': string;
    'data': OtcBankSupplementChecklistResponseData;
    'timestamp'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'OtcBankSupplementChecklistResponseData',
        },
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return OtcBankSupplementChecklistResponse.attributeTypeMap;
    }
}
