/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class OtcBankListItem {
    /**
     * Bank ID (required for order placement)
     */
    'id': string;
    /**
     * Bank account name
     */
    'bankAccountName': string;
    /**
     * Bank name
     */
    'bankName': string;
    /**
     * Bank country
     */
    'bankCountry'?: string;
    /**
     * Bank address
     */
    'bankAddress'?: string;
    /**
     * Bank code
     */
    'bankCode'?: string;
    /**
     * Branch code
     */
    'branchCode'?: string;
    /**
     * IBAN number
     */
    'iban'?: string;
    /**
     * SWIFT code
     */
    'swift'?: string;
    /**
     * Remittance routing number
     */
    'remittanceLineNumber'?: string;
    /**
     * Correspondent bank name
     */
    'agentBankName'?: string;
    /**
     * Correspondent bank SWIFT code
     */
    'agentBankSwift'?: string;
    /**
     * Submission time
     */
    'submitTime'?: string;
    /**
     * Update time
     */
    'updateTime'?: string;
    /**
     * Status
     */
    'status'?: string;
    /**
     * Document file type
     */
    'documentationFileType'?: string;
    /**
     * Remark
     */
    'memo'?: string;
    /**
     * Whether it is the default bank card. 1 - Yes, 0 - No
     */
    'isDefault'?: number;
    /**
     * Bank ID
     */
    'bankId'?: string;
    /**
     * Document file URL
     */
    'documentationFileKeyUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'bankAccountName',
            baseName: 'bank_account_name',
            type: 'string',
        },
        {
            name: 'bankName',
            baseName: 'bank_name',
            type: 'string',
        },
        {
            name: 'bankCountry',
            baseName: 'bank_country',
            type: 'string',
        },
        {
            name: 'bankAddress',
            baseName: 'bank_address',
            type: 'string',
        },
        {
            name: 'bankCode',
            baseName: 'bank_code',
            type: 'string',
        },
        {
            name: 'branchCode',
            baseName: 'branch_code',
            type: 'string',
        },
        {
            name: 'iban',
            baseName: 'iban',
            type: 'string',
        },
        {
            name: 'swift',
            baseName: 'swift',
            type: 'string',
        },
        {
            name: 'remittanceLineNumber',
            baseName: 'remittance_line_number',
            type: 'string',
        },
        {
            name: 'agentBankName',
            baseName: 'agent_bank_name',
            type: 'string',
        },
        {
            name: 'agentBankSwift',
            baseName: 'agent_bank_swift',
            type: 'string',
        },
        {
            name: 'submitTime',
            baseName: 'submit_time',
            type: 'string',
        },
        {
            name: 'updateTime',
            baseName: 'update_time',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'documentationFileType',
            baseName: 'documentation_file_type',
            type: 'string',
        },
        {
            name: 'memo',
            baseName: 'memo',
            type: 'string',
        },
        {
            name: 'isDefault',
            baseName: 'is_default',
            type: 'number',
        },
        {
            name: 'bankId',
            baseName: 'bank_id',
            type: 'string',
        },
        {
            name: 'documentationFileKeyUrl',
            baseName: 'documentation_file_key_url',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return OtcBankListItem.attributeTypeMap;
    }
}
