/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OtcOrderListCryptoCurrencyInfo } from './otcOrderListCryptoCurrencyInfo';
import { OtcOrderListFiatCurrencyInfo } from './otcOrderListFiatCurrencyInfo';

export class OtcOrderListItem {
    /**
     * Current time
     */
    'time'?: string;
    /**
     * Current timestamp
     */
    'timestamp'?: number;
    /**
     * orderId
     */
    'orderId'?: string;
    /**
     * Trade number
     */
    'tradeNo'?: string;
    /**
     * Quote direction buy/sell/all
     */
    'type'?: string;
    /**
     * Order Status
     */
    'status'?: string;
    'dbStatus'?: string;
    /**
     * Fiat type
     */
    'fiatCurrency'?: string;
    'fiatCurrencyInfo'?: OtcOrderListFiatCurrencyInfo;
    /**
     * Fiat amount
     */
    'fiatAmount'?: string;
    /**
     * Stablecoin
     */
    'cryptoCurrency'?: string;
    'cryptoCurrencyInfo'?: OtcOrderListCryptoCurrencyInfo;
    /**
     * Stablecoin amount
     */
    'cryptoAmount'?: string;
    /**
     * Exchange rate
     */
    'rate'?: string;
    /**
     * Remark
     */
    'transferRemark'?: string;
    /**
     * Bank account
     */
    'gateBankAccountIban'?: string;
    /**
     * Promotion code
     */
    'promotionCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'time',
            baseName: 'time',
            type: 'string',
        },
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'string',
        },
        {
            name: 'tradeNo',
            baseName: 'trade_no',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'dbStatus',
            baseName: 'db_status',
            type: 'string',
        },
        {
            name: 'fiatCurrency',
            baseName: 'fiat_currency',
            type: 'string',
        },
        {
            name: 'fiatCurrencyInfo',
            baseName: 'fiat_currency_info',
            type: 'OtcOrderListFiatCurrencyInfo',
        },
        {
            name: 'fiatAmount',
            baseName: 'fiat_amount',
            type: 'string',
        },
        {
            name: 'cryptoCurrency',
            baseName: 'crypto_currency',
            type: 'string',
        },
        {
            name: 'cryptoCurrencyInfo',
            baseName: 'crypto_currency_info',
            type: 'OtcOrderListCryptoCurrencyInfo',
        },
        {
            name: 'cryptoAmount',
            baseName: 'crypto_amount',
            type: 'string',
        },
        {
            name: 'rate',
            baseName: 'rate',
            type: 'string',
        },
        {
            name: 'transferRemark',
            baseName: 'transfer_remark',
            type: 'string',
        },
        {
            name: 'gateBankAccountIban',
            baseName: 'gate_bank_account_iban',
            type: 'string',
        },
        {
            name: 'promotionCode',
            baseName: 'promotion_code',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return OtcOrderListItem.attributeTypeMap;
    }
}
