/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Fiat Order Request Body
 */
export class OtcOrderRequest {
    /**
     * BUY for on-ramp, SELL for off-ramp
     */
    'type': string;
    /**
     * Quote direction returned by the quote API (used for order validation)
     */
    'side': string;
    /**
     * Cryptocurrency (supported currencies can be queried from the OTC web fiat quote page)
     */
    'cryptoCurrency': string;
    /**
     * Fiat currency (supported currencies can be queried from the OTC web fiat quote page)
     */
    'fiatCurrency': string;
    /**
     * Amount of cryptocurrency
     */
    'cryptoAmount': string;
    /**
     * Fiat amount
     */
    'fiatAmount': string;
    /**
     * Promotion code
     */
    'promotionCode'?: string;
    /**
     * Parameter returned by the quote API
     */
    'quoteToken': string;
    /**
     * The bank card ID used for placing the order; select it from the list returned by `GET /otc/bank_list` (or `GET /otc/bank/list`); the default card has `is_default=1`
     */
    'bankId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'type',
            baseName: 'type',
            type: 'string',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'string',
        },
        {
            name: 'cryptoCurrency',
            baseName: 'crypto_currency',
            type: 'string',
        },
        {
            name: 'fiatCurrency',
            baseName: 'fiat_currency',
            type: 'string',
        },
        {
            name: 'cryptoAmount',
            baseName: 'crypto_amount',
            type: 'string',
        },
        {
            name: 'fiatAmount',
            baseName: 'fiat_amount',
            type: 'string',
        },
        {
            name: 'promotionCode',
            baseName: 'promotion_code',
            type: 'string',
        },
        {
            name: 'quoteToken',
            baseName: 'quote_token',
            type: 'string',
        },
        {
            name: 'bankId',
            baseName: 'bank_id',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return OtcOrderRequest.attributeTypeMap;
    }
}
