/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OtcStableCoinOrderListItem } from './otcStableCoinOrderListItem';

export class OtcStableCoinOrderListResult {
    'total': number;
    'pageSize': number;
    'pageNumber': number;
    'totalPage': number;
    'list': Array<OtcStableCoinOrderListItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'total',
            baseName: 'total',
            type: 'number',
        },
        {
            name: 'pageSize',
            baseName: 'page_size',
            type: 'number',
        },
        {
            name: 'pageNumber',
            baseName: 'page_number',
            type: 'number',
        },
        {
            name: 'totalPage',
            baseName: 'total_page',
            type: 'number',
        },
        {
            name: 'list',
            baseName: 'list',
            type: 'Array<OtcStableCoinOrderListItem>',
        },
    ];

    static getAttributeTypeMap() {
        return OtcStableCoinOrderListResult.attributeTypeMap;
    }
}
