/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { P2pChatMessagePayload } from './p2pChatMessagePayload';

export class P2pChatMessage {
    /**
     * Whether the current user is the seller. `1`: yes; `0`: no.
     */
    'isSell'?: number;
    /**
     * Message type: `0` text; `1` file; `2` template; `3` order-share; `4` payment-share; `5` status update.
     */
    'msgType'?: number;
    /**
     * Message content; for file messages, usually URL or file key.
     */
    'msg'?: string;
    /**
     * Message sender username
     */
    'username'?: string;
    /**
     * Message timestamp
     */
    'timest'?: number;
    'msgObj'?: P2pChatMessagePayload;
    /**
     * Sender\'s crypto UID; system messages may use `System` or an empty string.
     */
    'uid'?: string;
    /**
     * Display type: `1` file message; `2` system message.
     */
    'type'?: number;
    /**
     * File link
     */
    'pic'?: string;
    /**
     * File key
     */
    'fileKey'?: string;
    /**
     * File type: `image` for images, `video` for videos.
     */
    'fileType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'isSell',
            baseName: 'is_sell',
            type: 'number',
        },
        {
            name: 'msgType',
            baseName: 'msg_type',
            type: 'number',
        },
        {
            name: 'msg',
            baseName: 'msg',
            type: 'string',
        },
        {
            name: 'username',
            baseName: 'username',
            type: 'string',
        },
        {
            name: 'timest',
            baseName: 'timest',
            type: 'number',
        },
        {
            name: 'msgObj',
            baseName: 'msg_obj',
            type: 'P2pChatMessagePayload',
        },
        {
            name: 'uid',
            baseName: 'uid',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'number',
        },
        {
            name: 'pic',
            baseName: 'pic',
            type: 'string',
        },
        {
            name: 'fileKey',
            baseName: 'file_key',
            type: 'string',
        },
        {
            name: 'fileType',
            baseName: 'file_type',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return P2pChatMessage.attributeTypeMap;
    }
}
