/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class P2pChatMessagePayload {
    /**
     * Order status when sending a message. Typical values: `OPEN`, `PAID`, `LOCKED`, `ACCEPT`, `BCLOSED`, `CANCEL`, `BECANCEL`, `SCLOSED`, `SCANCEL`.
     */
    'status'?: string;
    /**
     * Message content
     */
    'text'?: string;
    /**
     * Payment voucher
     */
    'paymentVoucher'?: Array<string>;
    /**
     * Cancel reason ID. `1` no longer want to buy; `2` cannot reach seller; `3` will not pay; `4` seller account not real; `5` payout account issue; `6` price mismatch; `7` mutually agreed cancel; `8` poor communication; `9` other; `10` seller cannot release with refund; `11` terms not met; `12` seller payout risk-controlled.
     */
    'reasonId'?: number;
    /**
     * Cancellation reason popup
     */
    'toastId'?: number;
    /**
     * Cancel reason description.
     */
    'reasonMemo'?: string;
    /**
     * Cancellation time
     */
    'cancelTime'?: number;
    /**
     * Seller confirmation of cancel reason: `0` pending; `1` confirmed; `2` rejected.
     */
    'sellerConfirm'?: number;
    /**
     * Payment method information ID
     */
    'id'?: string;
    /**
     * Payment method description
     */
    'accountDes'?: string;
    /**
     * Payment method type
     */
    'payType'?: string;
    /**
     * Payment method file link
     */
    'file'?: string;
    /**
     * Payment method file key
     */
    'fileKey'?: string;
    /**
     * Payment account or masked payment account.
     */
    'account'?: string;
    /**
     * Payment method note
     */
    'memo'?: string;
    /**
     * Payment method code
     */
    'code'?: string;
    /**
     * Payment method additional note
     */
    'memoExt'?: string;
    /**
     * Payment method tip
     */
    'tradeTips'?: string;
    /**
     * Payment method username
     */
    'realName'?: string;
    /**
     * Whether the payment method was deleted. `1`: deleted; `0`: not deleted.
     */
    'isDelete'?: number;
    /**
     * Payment method full name
     */
    'payName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'status',
            baseName: 'status',
            type: 'string',
        },
        {
            name: 'text',
            baseName: 'text',
            type: 'string',
        },
        {
            name: 'paymentVoucher',
            baseName: 'payment_voucher',
            type: 'Array<string>',
        },
        {
            name: 'reasonId',
            baseName: 'reason_id',
            type: 'number',
        },
        {
            name: 'toastId',
            baseName: 'toast_id',
            type: 'number',
        },
        {
            name: 'reasonMemo',
            baseName: 'reason_memo',
            type: 'string',
        },
        {
            name: 'cancelTime',
            baseName: 'cancel_time',
            type: 'number',
        },
        {
            name: 'sellerConfirm',
            baseName: 'seller_confirm',
            type: 'number',
        },
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        },
        {
            name: 'accountDes',
            baseName: 'account_des',
            type: 'string',
        },
        {
            name: 'payType',
            baseName: 'pay_type',
            type: 'string',
        },
        {
            name: 'file',
            baseName: 'file',
            type: 'string',
        },
        {
            name: 'fileKey',
            baseName: 'file_key',
            type: 'string',
        },
        {
            name: 'account',
            baseName: 'account',
            type: 'string',
        },
        {
            name: 'memo',
            baseName: 'memo',
            type: 'string',
        },
        {
            name: 'code',
            baseName: 'code',
            type: 'string',
        },
        {
            name: 'memoExt',
            baseName: 'memo_ext',
            type: 'string',
        },
        {
            name: 'tradeTips',
            baseName: 'trade_tips',
            type: 'string',
        },
        {
            name: 'realName',
            baseName: 'real_name',
            type: 'string',
        },
        {
            name: 'isDelete',
            baseName: 'is_delete',
            type: 'number',
        },
        {
            name: 'payName',
            baseName: 'pay_name',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return P2pChatMessagePayload.attributeTypeMap;
    }
}
