/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { P2pMerchantBooksPlaceBizPushOrderResponseData } from './p2pMerchantBooksPlaceBizPushOrderResponseData';

export class P2pMerchantBooksPlaceBizPushOrderResponse {
    /**
     * Response timestamp.
     */
    'timestamp'?: number;
    /**
     * Placeholder for request method.
     */
    'method'?: string;
    /**
     * Response code. 0 means success; 70305102 means the advertisement trade terms or auto reply hit off-platform traffic diversion risk control
     */
    'code'?: number;
    /**
     * Response message
     */
    'message'?: string;
    'data'?: P2pMerchantBooksPlaceBizPushOrderResponseData;
    /**
     * API version.
     */
    'version'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
        {
            name: 'method',
            baseName: 'method',
            type: 'string',
        },
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'P2pMerchantBooksPlaceBizPushOrderResponseData',
        },
        {
            name: 'version',
            baseName: 'version',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return P2pMerchantBooksPlaceBizPushOrderResponse.attributeTypeMap;
    }
}
