/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class P2pTransactionActionResponse {
    /**
     * Response timestamp.
     */
    'timestamp'?: number;
    /**
     * Placeholder for request method.
     */
    'method'?: string;
    /**
     * Response code, 0 means success
     */
    'code'?: number;
    /**
     * Response message
     */
    'message'?: string;
    /**
     * Empty object on success.
     */
    'data'?: object;
    /**
     * API version.
     */
    'version'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
        {
            name: 'method',
            baseName: 'method',
            type: 'string',
        },
        {
            name: 'code',
            baseName: 'code',
            type: 'number',
        },
        {
            name: 'message',
            baseName: 'message',
            type: 'string',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'object',
        },
        {
            name: 'version',
            baseName: 'version',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return P2pTransactionActionResponse.attributeTypeMap;
    }
}
