/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { P2pTransactionListItem } from './p2pTransactionListItem';
import { P2pTransactionTimeMarker } from './p2pTransactionTimeMarker';

export class P2pTransactionListResult {
    'list'?: Array<P2pTransactionListItem>;
    /**
     * Countdown time
     */
    'transTime'?: Array<P2pTransactionTimeMarker>;
    /**
     * Number of orders
     */
    'count'?: number;
    /**
     * Export count
     */
    'exportedNum'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'list',
            baseName: 'list',
            type: 'Array<P2pTransactionListItem>',
        },
        {
            name: 'transTime',
            baseName: 'trans_time',
            type: 'Array<P2pTransactionTimeMarker>',
        },
        {
            name: 'count',
            baseName: 'count',
            type: 'number',
        },
        {
            name: 'exportedNum',
            baseName: 'exported_num',
            type: 'number',
        },
    ];

    static getAttributeTypeMap() {
        return P2pTransactionListResult.attributeTypeMap;
    }
}
