/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Order response
 */
export class PlaceOrderResponse {
    /**
     * Order ID
     */
    'orderId'?: string;
    /**
     * Order Status - `0` : All - `1` : Processing - `2` : Successful - `3` : Failed - `4` : Cancelled - `5` : Buy order placed but transfer not completed - `6` : Order cancelled but transfer not completed
     */
    'status'?: number;
    /**
     * Buy or sell orders - buy - sell
     */
    'side'?: string;
    /**
     * Trading mode affects slippage selection - `speed` : Smart mode - `custom` : Custom mode, uses `slippage` parameter
     */
    'gasMode'?: string;
    /**
     * Creation timestamp
     */
    'createTime'?: number;
    /**
     * Trade Quantity - `side` : `buy` refers to the quote currency, i.e., `USDT` - `side` : `sell` refers to the base currency
     */
    'amount'?: string;
    /**
     * Token contract address
     */
    'tokenAddress'?: string;
    /**
     * Blockchain name
     */
    'chain'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'orderId',
            baseName: 'order_id',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'number',
        },
        {
            name: 'side',
            baseName: 'side',
            type: 'string',
        },
        {
            name: 'gasMode',
            baseName: 'gas_mode',
            type: 'string',
        },
        {
            name: 'createTime',
            baseName: 'create_time',
            type: 'number',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'tokenAddress',
            baseName: 'token_address',
            type: 'string',
        },
        {
            name: 'chain',
            baseName: 'chain',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return PlaceOrderResponse.attributeTypeMap;
    }
}
