/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Position information
 */
export class PositionListDataList {
    /**
     * Position ID
     */
    'positionId'?: number;
    /**
     * Trading market code
     */
    'symbol'?: string;
    /**
     * Market description
     */
    'symbolDesc'?: string;
    /**
     * Used margin
     */
    'margin'?: string;
    /**
     * Unrealized PNL
     */
    'unrealizedPnl'?: string;
    /**
     * Unrealized return rate
     */
    'unrealizedPnlRate'?: string;
    /**
     * Position size
     */
    'volume'?: string;
    /**
     * Average Opening Price
     */
    'priceOpen'?: string;
    /**
     * Position direction (Long=long position, Short=short position)
     */
    'positionDir'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'positionId',
            baseName: 'position_id',
            type: 'number',
        },
        {
            name: 'symbol',
            baseName: 'symbol',
            type: 'string',
        },
        {
            name: 'symbolDesc',
            baseName: 'symbol_desc',
            type: 'string',
        },
        {
            name: 'margin',
            baseName: 'margin',
            type: 'string',
        },
        {
            name: 'unrealizedPnl',
            baseName: 'unrealized_pnl',
            type: 'string',
        },
        {
            name: 'unrealizedPnlRate',
            baseName: 'unrealized_pnl_rate',
            type: 'string',
        },
        {
            name: 'volume',
            baseName: 'volume',
            type: 'string',
        },
        {
            name: 'priceOpen',
            baseName: 'price_open',
            type: 'string',
        },
        {
            name: 'positionDir',
            baseName: 'position_dir',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return PositionListDataList.attributeTypeMap;
    }
}
