/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Preview the selling side of the request: currency + quantity. The semantics are similar to `CreateParam` on the `from` side (both `asset` + `amount`).
 */
export class PreviewFromParam {
    /**
     * The currency symbol to be swapped out.
     */
    'asset': string;
    /**
     * The currency swap quantity, decimal string.
     */
    'amount': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'asset',
            baseName: 'asset',
            type: 'string',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return PreviewFromParam.attributeTypeMap;
    }
}
