/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RecommendV2Scheme } from './recommendV2Scheme';

export class RecommendV2Strategy {
    'name': string;
    'priority': number;
    'schemes': Array<RecommendV2Scheme>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'name',
            baseName: 'name',
            type: 'string',
        },
        {
            name: 'priority',
            baseName: 'priority',
            type: 'number',
        },
        {
            name: 'schemes',
            baseName: 'schemes',
            type: 'Array<RecommendV2Scheme>',
        },
    ];

    static getAttributeTypeMap() {
        return RecommendV2Strategy.attributeTypeMap;
    }
}
