/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Spot martingale creation parameters (serialized fields aligned with `MartingaleBot`). - **Stop-loss**: use `stop_loss_per_cycle` (ratio per round), same as the app; **do not** use `stop_loss_price`. - Optional **`trigger_price`**: trigger price. - If `stop_loss_per_cycle` is passed and > 0, the server validates roughly between `0.001` and `0.9999` (same as `check_martingale`).
 */
export class SpotMartingaleCreateParams {
    'investAmount': string;
    /**
     * Add-position deviation ratio as a decimal string (e.g. a 2% drop is `0.02`).
     */
    'priceDeviation': string;
    'maxOrders': number;
    /**
     * Take-profit ratio per round as a decimal string.
     */
    'takeProfitRatio': string;
    /**
     * Stop-loss ratio per round as a decimal string; optional; aligned with app `stop_loss_per_cycle`.
     */
    'stopLossPerCycle'?: string;
    /**
     * Trigger price; optional.
     */
    'triggerPrice'?: string;
    'profitSharingRatio'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'investAmount',
            baseName: 'invest_amount',
            type: 'string',
        },
        {
            name: 'priceDeviation',
            baseName: 'price_deviation',
            type: 'string',
        },
        {
            name: 'maxOrders',
            baseName: 'max_orders',
            type: 'number',
        },
        {
            name: 'takeProfitRatio',
            baseName: 'take_profit_ratio',
            type: 'string',
        },
        {
            name: 'stopLossPerCycle',
            baseName: 'stop_loss_per_cycle',
            type: 'string',
        },
        {
            name: 'triggerPrice',
            baseName: 'trigger_price',
            type: 'string',
        },
        {
            name: 'profitSharingRatio',
            baseName: 'profit_sharing_ratio',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return SpotMartingaleCreateParams.attributeTypeMap;
    }
}
