/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Fund Transfer Request Body
 */
export class TradFiTransactionRequest {
    /**
     * Asset type, e.g., USDT, currently only USDT is supported
     */
    'asset': string;
    /**
     * Change Quantity, supports up to two decimal places
     */
    'change': string;
    /**
     * Transaction Type (deposit - transfer in, withdraw - transfer out)
     */
    'type': TradFiTransactionRequest.Type;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'asset',
            baseName: 'asset',
            type: 'string',
        },
        {
            name: 'change',
            baseName: 'change',
            type: 'string',
        },
        {
            name: 'type',
            baseName: 'type',
            type: 'TradFiTransactionRequest.Type',
        },
    ];

    static getAttributeTypeMap() {
        return TradFiTransactionRequest.attributeTypeMap;
    }
}

export namespace TradFiTransactionRequest {
    export enum Type {
        Deposit = <any>'deposit',
        Withdraw = <any>'withdraw',
    }
}
