/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateOrderData } from './updateOrderData';

/**
 * Order modification result
 */
export class UpdateOrder {
    /**
     * Server timestamp (milliseconds)
     */
    'timestamp'?: number;
    'data'?: UpdateOrderData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'timestamp',
            baseName: 'timestamp',
            type: 'number',
        },
        {
            name: 'data',
            baseName: 'data',
            type: 'UpdateOrderData',
        },
    ];

    static getAttributeTypeMap() {
        return UpdateOrder.attributeTypeMap;
    }
}
