/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UpdateTrailOrder {
    /**
     * Order ID
     */
    'id': bigint;
    /**
     * Total trading quantity in contracts, positive for buy, negative for sell, 0 means no modification
     */
    'amount'?: string;
    /**
     * Activation price, 0 means trigger immediately, empty means no modification
     */
    'activationPrice'?: string;
    /**
     * true: activate when market price >= activation price, false: <= activation price, empty means no modification
     */
    'isGteStr'?: string;
    /**
     * Activation price type, not provided or 0 means no modification, 1-latest price, 2-index price, 3-mark price
     */
    'priceType'?: UpdateTrailOrder.PriceType;
    /**
     * Callback ratio or price distance, e.g., `0.1` or `0.1%`; empty means no modification
     */
    'priceOffset'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'bigint',
        },
        {
            name: 'amount',
            baseName: 'amount',
            type: 'string',
        },
        {
            name: 'activationPrice',
            baseName: 'activation_price',
            type: 'string',
        },
        {
            name: 'isGteStr',
            baseName: 'is_gte_str',
            type: 'string',
        },
        {
            name: 'priceType',
            baseName: 'price_type',
            type: 'UpdateTrailOrder.PriceType',
        },
        {
            name: 'priceOffset',
            baseName: 'price_offset',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return UpdateTrailOrder.attributeTypeMap;
    }
}

export namespace UpdateTrailOrder {
    export enum PriceType {
        NUMBER_0 = <any>0,
        NUMBER_1 = <any>1,
        NUMBER_2 = <any>2,
        NUMBER_3 = <any>3,
    }
}
