/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Upload chat file request
 */
export class UploadChatFile {
    /**
     * File MIME type: supports `image/jpeg`, `image/jpg`, `image/png`, `video/mp4`.
     */
    'imageContentType': UploadChatFile.ImageContentType;
    /**
     * Base64 file content; max 20 MB.
     */
    'base64Img': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
        {
            name: 'imageContentType',
            baseName: 'image_content_type',
            type: 'UploadChatFile.ImageContentType',
        },
        {
            name: 'base64Img',
            baseName: 'base64_img',
            type: 'string',
        },
    ];

    static getAttributeTypeMap() {
        return UploadChatFile.attributeTypeMap;
    }
}

export namespace UploadChatFile {
    export enum ImageContentType {
        ImageJpeg = <any>'image/jpeg',
        ImageJpg = <any>'image/jpg',
        ImagePng = <any>'image/png',
        VideoMp4 = <any>'video/mp4',
    }
}
