/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* eslint-disable @typescript-eslint/no-floating-promises */

import {
    Authentication,
    GateApiV4Auth,
    HttpBasicAuth,
    HttpBearerAuth,
    OAuth,
    ObjectSerializer,
    serializeRequestData,
} from '../model/models';

import JSONBig from 'json-bigint';
import globalAxios, { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

const JSONBigInt = JSONBig({ useNativeBigInt: true });

function isJsonRequestBody(data: any): boolean {
    if (data === undefined || data === null) {
        return false;
    }
    if (typeof data === 'string' || Buffer.isBuffer(data) || data instanceof ArrayBuffer || ArrayBuffer.isView(data)) {
        return false;
    }
    if (typeof FormData !== 'undefined' && data instanceof FormData) {
        return false;
    }
    if (typeof data.pipe === 'function') {
        return false;
    }
    return true;
}

function ensureJsonContentType(headers: any): void {
    if (!headers) {
        return;
    }
    if (typeof headers.setContentType === 'function') {
        headers.setContentType('application/json');
        return;
    }
    if (headers['Content-Type'] === undefined && headers['content-type'] === undefined) {
        headers['Content-Type'] = 'application/json';
    }
}

export class ApiClient {
    protected _basePath: string = 'https://api.gateio.ws/api/v4';
    protected _defaultHeaders: any = {};

    protected authentications: { [key: string]: Authentication } = {
        apiv4: new GateApiV4Auth(),
    };

    constructor(
        basePath?: string,
        protected axiosInstance: AxiosInstance = globalAxios,
    ) {
        this._basePath = basePath || this._basePath;

        // Set default X-Gate-Size-Decimal header for futures API
        this._defaultHeaders['X-Gate-Size-Decimal'] = '1';

        this.axiosInstance.defaults.transformResponse = [
            (data) => {
                try {
                    return JSONBigInt.parse(data);
                } catch (error) {
                    console.error('Failed to parse JSON:', error);
                    return data;
                }
            },
        ];
        this.axiosInstance.defaults.transformRequest = [
            (data, headers) => {
                if (isJsonRequestBody(data)) {
                    ensureJsonContentType(headers);
                }
                return serializeRequestData(data);
            },
        ];
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    get basePath() {
        return this._basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    public setApiKeySecret(key: string, secret: string) {
        let auth = this.authentications['apiv4'] as GateApiV4Auth;
        auth.key = key;
        auth.secret = secret;
    }

    public applyToRequest(config: AxiosRequestConfig, authSettings: Array<string>): AxiosRequestConfig {
        for (let auth of authSettings) {
            let authenticator = this.authentications[auth];
            if (authenticator) {
                config = authenticator.applyToRequest(config);
            }
        }
        return config;
    }

    public async request<T>(
        config: AxiosRequestConfig,
        responseType: string,
        authSettings: Array<string>,
    ): Promise<{ response: AxiosResponse; body: T }> {
        return Promise.resolve(config)
            .then((c) => this.applyToRequest(c, authSettings))
            .then((c) => {
                return this.axiosInstance.request(c).then((rsp) => {
                    let body = rsp.data;
                    if (responseType.length > 0) {
                        body = ObjectSerializer.deserialize(rsp.data, responseType);
                    }
                    return { response: rsp, body: body };
                });
            });
    }
}
