/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-locals */
import { ApiResponseAssetSwapConfig } from '../model/apiResponseAssetSwapConfig';
import { ApiResponseAssetSwapEvaluate } from '../model/apiResponseAssetSwapEvaluate';
import { ApiResponseAssetSwapListAssets } from '../model/apiResponseAssetSwapListAssets';
import { ApiResponseAssetSwapOrderCreateV1 } from '../model/apiResponseAssetSwapOrderCreateV1';
import { ApiResponseAssetSwapOrderListV1 } from '../model/apiResponseAssetSwapOrderListV1';
import { ApiResponseAssetSwapOrderPreviewV1 } from '../model/apiResponseAssetSwapOrderPreviewV1';
import { ApiResponseAssetSwapOrderQueryV1 } from '../model/apiResponseAssetSwapOrderQueryV1';
import { OrderCreateV1Req } from '../model/orderCreateV1Req';
import { OrderPreviewV1Req } from '../model/orderPreviewV1Req';
import { ObjectSerializer } from '../model/models';
import { ApiClient } from './apiClient';
import { AxiosRequestConfig, AxiosResponse } from 'axios';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export class AssetswapApi {
    protected client: ApiClient;

    constructor(client?: ApiClient) {
        if (client) {
            this.client = client;
        } else {
            this.client = new ApiClient();
        }
    }

    /**
     * Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME <EMAIL@ADDRESS> Language: en Language-Team: en <L@li.org> Plural-Forms: nplurals=2; plural=(n !=1) MIME-Version: 1.0 Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @summary Portfolio optimization — currency list
     */
    public async listAssetSwapAssets(): Promise<{ response: AxiosResponse; body: ApiResponseAssetSwapListAssets }> {
        const localVarPath = this.client.basePath + '/asset-swap/asset/list';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<ApiResponseAssetSwapListAssets>(
            config,
            'ApiResponseAssetSwapListAssets',
            authSettings,
        );
    }

    /**
     * Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME <EMAIL@ADDRESS> Language: en Language-Team: en <L@li.org> Plural-Forms: nplurals=2; plural=(n !=1) MIME-Version: 1.0 Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @summary Portfolio optimization — configuration
     */
    public async getAssetSwapConfig(): Promise<{ response: AxiosResponse; body: ApiResponseAssetSwapConfig }> {
        const localVarPath = this.client.basePath + '/asset-swap/config';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<ApiResponseAssetSwapConfig>(config, 'ApiResponseAssetSwapConfig', authSettings);
    }

    /**
     * Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME <EMAIL@ADDRESS> Language: en Language-Team: en <L@li.org> Plural-Forms: nplurals=2; plural=(n !=1) MIME-Version: 1.0 Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @summary Portfolio optimization — valuation
     * @param opts Optional parameters
     * @param opts.maxEvaluateValue Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.cursor Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.size Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     */
    public async evaluateAssetSwap(opts?: {
        maxEvaluateValue?: number;
        cursor?: string;
        size?: number;
    }): Promise<{ response: AxiosResponse; body: ApiResponseAssetSwapEvaluate }> {
        const localVarPath = this.client.basePath + '/asset-swap/evaluate';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.maxEvaluateValue !== undefined) {
            let maxEvaluateValueSerialized = ObjectSerializer.serialize(opts.maxEvaluateValue, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(maxEvaluateValueSerialized)) {
                maxEvaluateValueSerialized = maxEvaluateValueSerialized.join(',');
            }
            localVarQueryParameters['max_evaluate_value'] = maxEvaluateValueSerialized;
        }

        if (opts.cursor !== undefined) {
            let cursorSerialized = ObjectSerializer.serialize(opts.cursor, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(cursorSerialized)) {
                cursorSerialized = cursorSerialized.join(',');
            }
            localVarQueryParameters['cursor'] = cursorSerialized;
        }

        if (opts.size !== undefined) {
            let sizeSerialized = ObjectSerializer.serialize(opts.size, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(sizeSerialized)) {
                sizeSerialized = sizeSerialized.join(',');
            }
            localVarQueryParameters['size'] = sizeSerialized;
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<ApiResponseAssetSwapEvaluate>(config, 'ApiResponseAssetSwapEvaluate', authSettings);
    }

    /**
     * 将账户内若干源币种按指定数量换入目标币种侧配置，**正式下单前强烈建议先调用** `POST /asset-swap/order/preview` **且 `code=0` 后再用一致的语义提交本接口**。  **请求体不含 `ratio`** - 本接口 `OrderCreateV1Req` 仅含 `from` / `to`，且数组元素均为 `CreateParam`（**仅** `asset` + `amount`）。**请勿**在下单 JSON 中传入 `ratio`；比例字段 `ratio` 只存在于预览接口 `OrderPreviewV1Req.to`（`PreviewToParam`）。  **与预览接口的关键差异（易错点）** - 本接口 `to` 数组元素为 `CreateParam`：**`asset` + `amount`（目标侧数量，十进制字符串）**。 - 预览接口 `to` 为 **`asset` + `ratio`（比例字符串）**，**二者不可混用**：不要把预览里的 `ratio` 原样填到下单的 `amount`，也不要把下单的 `amount` 当成预览的 `ratio`。  **推荐调用顺序** 1. `GET /asset-swap/asset/list`：确认币种支持。 2. `GET /asset-swap/config`：读取 `recommend` / `recommend_v2`（如 `recommend_v2.market` 下某策略的 `schemes`，将 `scheme.name` 作为目标 `asset`、`scheme.ratio` 仅用于 **preview** 的 `to[].ratio`）。 3. `GET /asset-swap/evaluate`（可选）：参考可卖数量。 4. `POST /asset-swap/order/preview`：`from` 与 `to`（比例）构造询价。 5. 预览成功后，按产品/服务端约定将预览结果映射为下单的 `from`/`to`（**均为 amount**）再调用本接口。  **字段约定** - `from`：卖出侧，每项为 `asset` + `amount`（字符串，十进制，表示该币种卖出数量）。 - `to`：买入/目标侧，每项为 `asset` + **`amount`**（字符串，十进制，表示该目标币种侧数量；语义与预览的 `ratio` 不同）。 - 本接口仅校验上述 `amount` 的精度与范围；不满足时返回非 0 `code` 及 `message`。预览侧 `to[].ratio` 的校验规则见 `POST /asset-swap/order/preview` 文档。
     * @summary Portfolio optimization — place order
     * @param orderCreateV1Req 下单请求体（&#x60;OrderCreateV1Req&#x60;）。**无 &#x60;ratio&#x60; 字段**；&#x60;from&#x60;/&#x60;to&#x60; 每项仅 &#x60;asset&#x60; + &#x60;amount&#x60;。&#x60;to&#x60; 使用目标侧**数量** &#x60;amount&#x60;，与 preview 中 &#x60;to&#x60; 的 **ratio**（比例）语义不同，勿混用。
     */
    public async createAssetSwapOrderV1(
        orderCreateV1Req: OrderCreateV1Req,
    ): Promise<{ response: AxiosResponse; body: ApiResponseAssetSwapOrderCreateV1 }> {
        const localVarPath = this.client.basePath + '/asset-swap/order/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'orderCreateV1Req' is not null or undefined
        if (orderCreateV1Req === null || orderCreateV1Req === undefined) {
            throw new Error(
                'Required parameter orderCreateV1Req was null or undefined when calling createAssetSwapOrderV1.',
            );
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(orderCreateV1Req, 'OrderCreateV1Req'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<ApiResponseAssetSwapOrderCreateV1>(
            config,
            'ApiResponseAssetSwapOrderCreateV1',
            authSettings,
        );
    }

    /**
     * Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME <EMAIL@ADDRESS> Language: en Language-Team: en <L@li.org> Plural-Forms: nplurals=2; plural=(n !=1) MIME-Version: 1.0 Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @summary Portfolio optimization — order list
     * @param opts Optional parameters
     * @param opts.from Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.to Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.status Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.offset Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.size Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.sortMode Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @param opts.orderBy Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     */
    public async listAssetSwapOrdersV1(opts?: {
        from?: number;
        to?: number;
        status?: number;
        offset?: number;
        size?: number;
        sortMode?: number;
        orderBy?: number;
    }): Promise<{ response: AxiosResponse; body: ApiResponseAssetSwapOrderListV1 }> {
        const localVarPath = this.client.basePath + '/asset-swap/order/list';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.from !== undefined) {
            let fromSerialized = ObjectSerializer.serialize(opts.from, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(fromSerialized)) {
                fromSerialized = fromSerialized.join(',');
            }
            localVarQueryParameters['from'] = fromSerialized;
        }

        if (opts.to !== undefined) {
            let toSerialized = ObjectSerializer.serialize(opts.to, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(toSerialized)) {
                toSerialized = toSerialized.join(',');
            }
            localVarQueryParameters['to'] = toSerialized;
        }

        if (opts.status !== undefined) {
            let statusSerialized = ObjectSerializer.serialize(opts.status, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(statusSerialized)) {
                statusSerialized = statusSerialized.join(',');
            }
            localVarQueryParameters['status'] = statusSerialized;
        }

        if (opts.offset !== undefined) {
            let offsetSerialized = ObjectSerializer.serialize(opts.offset, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(offsetSerialized)) {
                offsetSerialized = offsetSerialized.join(',');
            }
            localVarQueryParameters['offset'] = offsetSerialized;
        }

        if (opts.size !== undefined) {
            let sizeSerialized = ObjectSerializer.serialize(opts.size, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(sizeSerialized)) {
                sizeSerialized = sizeSerialized.join(',');
            }
            localVarQueryParameters['size'] = sizeSerialized;
        }

        if (opts.sortMode !== undefined) {
            let sortModeSerialized = ObjectSerializer.serialize(opts.sortMode, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(sortModeSerialized)) {
                sortModeSerialized = sortModeSerialized.join(',');
            }
            localVarQueryParameters['sort_mode'] = sortModeSerialized;
        }

        if (opts.orderBy !== undefined) {
            let orderBySerialized = ObjectSerializer.serialize(opts.orderBy, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(orderBySerialized)) {
                orderBySerialized = orderBySerialized.join(',');
            }
            localVarQueryParameters['order_by'] = orderBySerialized;
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<ApiResponseAssetSwapOrderListV1>(
            config,
            'ApiResponseAssetSwapOrderListV1',
            authSettings,
        );
    }

    /**
     * 根据卖出币种数量与**目标分配比例**估算成交与费用，**不写入订单**。`code=0` 时 `data` 含预估 `order` 与 `transaction_fee`。  **与下单接口的关键差异（易错点）** - 本接口 `to` 数组元素为 `PreviewToParam`：**`asset` + `ratio`（比例，十进制字符串）**，表示目标币种在组合中的权重/占比。 - 下单接口 `POST /asset-swap/order/create` 的 `to` 为 **`asset` + `amount`（绝对数量）**，**不是** `ratio`。调用方切勿把两套字段混用。  **如何构造 `to`（ratio）** - 优先从 `GET /asset-swap/config` 的 `data.recommend_v2` 取值：按分组键（如 `market`、`faith`、`conservative`）找到策略列表中的某条 `RecommendV2Strategy`（如 `name` 为 `top2`），将其 `schemes` 映射为预览请求：   - `to[].asset` ← `scheme.name`（目标币种符号）   - `to[].ratio` ← `scheme.ratio`（与配置一致的比例字符串） - 亦可使用 `recommend` 下扁平 map（币种 → 比例字符串）自行展开为多元素 `to`（每项一个 `asset` + `ratio`）。 - 多目标时各 `ratio` 建议与前端/运营配置一致；是否需加总为 1 以服务端校验为准。  **`from`（卖出侧）** - 每项为 `asset` + `amount`（字符串，十进制），表示本次参与换出的该币种数量。币种应在 `GET /asset-swap/asset/list` 支持范围内；数量级过小或市场深度不足时可能返回非 0 `code`（如无法询价）。  **与下单的衔接** - 预览成功后，将业务允许的预览结果转换为下单所需的 **`from`/`to` 全为 amount** 的请求体再调用 create（具体映射规则以产品文档或服务端约定为准）。
     * @summary Portfolio optimization — preview
     * @param orderPreviewV1Req 预览请求体。&#x60;to&#x60; 必须为 **ratio**；与 create 的 **amount** 语义不同。
     */
    public async previewAssetSwapOrderV1(
        orderPreviewV1Req: OrderPreviewV1Req,
    ): Promise<{ response: AxiosResponse; body: ApiResponseAssetSwapOrderPreviewV1 }> {
        const localVarPath = this.client.basePath + '/asset-swap/order/preview';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'orderPreviewV1Req' is not null or undefined
        if (orderPreviewV1Req === null || orderPreviewV1Req === undefined) {
            throw new Error(
                'Required parameter orderPreviewV1Req was null or undefined when calling previewAssetSwapOrderV1.',
            );
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(orderPreviewV1Req, 'OrderPreviewV1Req'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<ApiResponseAssetSwapOrderPreviewV1>(
            config,
            'ApiResponseAssetSwapOrderPreviewV1',
            authSettings,
        );
    }

    /**
     * Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME <EMAIL@ADDRESS> Language: en Language-Team: en <L@li.org> Plural-Forms: nplurals=2; plural=(n !=1) MIME-Version: 1.0 Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     * @summary Portfolio optimization — query order
     * @param orderId Project-Id-Version: GateApiTools 1.0.0 Report-Msgid-Bugs-To: EMAIL@ADDRESS POT-Creation-Date: 2025-11-12 18:14+0800 PO-Revision-Date: 2019-01-02 17:30+0800 Last-Translator: FULL NAME &lt;EMAIL@ADDRESS&gt; Language: en Language-Team: en &lt;L@li.org&gt; Plural-Forms: nplurals&#x3D;2; plural&#x3D;(n !&#x3D;1) MIME-Version: 1.0 Content-Type: text/plain; charset&#x3D;utf-8 Content-Transfer-Encoding: 8bit Generated-By: Babel 2.8.0
     */
    public async getAssetSwapOrderV1(
        orderId: string,
    ): Promise<{ response: AxiosResponse; body: ApiResponseAssetSwapOrderQueryV1 }> {
        const localVarPath =
            this.client.basePath +
            '/asset-swap/order/{order_id}'.replace('{' + 'order_id' + '}', encodeURIComponent(String(orderId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'orderId' is not null or undefined
        if (orderId === null || orderId === undefined) {
            throw new Error('Required parameter orderId was null or undefined when calling getAssetSwapOrderV1.');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<ApiResponseAssetSwapOrderQueryV1>(
            config,
            'ApiResponseAssetSwapOrderQueryV1',
            authSettings,
        );
    }
}
