/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-locals */
import { AIHubCreateSuccessResponse } from '../model/aIHubCreateSuccessResponse';
import { AIHubDiscoverSuccessResponse } from '../model/aIHubDiscoverSuccessResponse';
import { AIHubPortfolioDetailSuccessResponse } from '../model/aIHubPortfolioDetailSuccessResponse';
import { AIHubPortfolioRunningSuccessResponse } from '../model/aIHubPortfolioRunningSuccessResponse';
import { AIHubPortfolioStopRequest } from '../model/aIHubPortfolioStopRequest';
import { AIHubPortfolioStopSuccessResponse } from '../model/aIHubPortfolioStopSuccessResponse';
import { ContractMartingaleCreateRequest } from '../model/contractMartingaleCreateRequest';
import { FuturesGridCreateRequest } from '../model/futuresGridCreateRequest';
import { InfiniteGridCreateRequest } from '../model/infiniteGridCreateRequest';
import { MarginGridCreateRequest } from '../model/marginGridCreateRequest';
import { SpotGridCreateRequest } from '../model/spotGridCreateRequest';
import { SpotMartingaleCreateRequest } from '../model/spotMartingaleCreateRequest';
import { ObjectSerializer } from '../model/models';
import { ApiClient } from './apiClient';
import { AxiosRequestConfig, AxiosResponse } from 'axios';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export class BotApi {
    protected client: ApiClient;

    constructor(client?: ApiClient) {
        if (client) {
            this.client = client;
        } else {
            this.client = new ApiClient();
        }
    }

    /**
     * discover 域唯一正式接口。  支持场景： - `top1` - `bundle` - `filter` - `refresh`  约束： - 主动推荐池仅包含 `spot_grid`、`futures_grid`、`spot_martingale` - 可返回但不主动推荐 `infinite_grid`、`margin_grid` - 不得返回 `contract_martingale`、`smart-position`、`spot-future-arbitrage` - `scene=filter` 时只允许按 `market`、`backtest_apr_gte`、`max_drawdown_lte` 过滤 - `scene=refresh` 通过 `refresh_recommendation_id` 承接刷新上下文；正式最小格式只要求 `strategy_type|market` - 若上游直接透传上一条推荐的 `recommendation_id`，其中第三段 `backtest_id` 当前会被忽略
     * @summary Get AIHub strategy recommendations
     * @param opts Optional parameters
     * @param opts.market Trading pair, such as &#x60;BTC_USDT&#x60;
     * @param opts.strategyType Recommended target policy type; &#x60;contract_martingale&#x60; not allowed
     * @param opts.direction Market direction
     * @param opts.investAmount Investment amount, string transparent transmission
     * @param opts.scene Recommended scenario; when empty, bot-service can automatically infer according to the implementation logic.
     * @param opts.refreshRecommendationId It is recommended to refresh the context. Used when &#x60;scene&#x3D;refresh&#x60; is used; when &#x60;scene&#x60; is empty but the field exists, bot-service will also automatically determine as &#x60;refresh&#x60;. The official minimum format is &#x60;strategy_type|market&#x60;; if the &#x60;recommendation_id&#x60; of the previous recommendation is directly passed through, the third paragraph &#x60;backtest_id&#x60; will be ignored.
     * @param opts.limit Return quantity; when &#x60;scene&#x3D;filter&#x60; is used, the actual results are up to 10
     * @param opts.maxDrawdownLte Maximum drawdown limit
     * @param opts.backtestAprGte Backtest annualized lower limit
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async getAIHubStrategyRecommend(opts?: {
        market?: string;
        strategyType?: 'spot_grid' | 'margin_grid' | 'infinite_grid' | 'futures_grid' | 'spot_martingale';
        direction?: 'buy' | 'sell' | 'neutral';
        investAmount?: string;
        scene?: 'top1' | 'bundle' | 'filter' | 'refresh';
        refreshRecommendationId?: string;
        limit?: number;
        maxDrawdownLte?: string;
        backtestAprGte?: string;
        xGateServiceId?: string;
        xGateAppLang?: string;
        xRequestId?: string;
        xTraceId?: string;
    }): Promise<{ response: AxiosResponse; body: AIHubDiscoverSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/strategy/recommend';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.market !== undefined) {
            let marketSerialized = ObjectSerializer.serialize(opts.market, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(marketSerialized)) {
                marketSerialized = marketSerialized.join(',');
            }
            localVarQueryParameters['market'] = marketSerialized;
        }

        if (opts.strategyType !== undefined) {
            let strategyTypeSerialized = ObjectSerializer.serialize(
                opts.strategyType,
                "'spot_grid' | 'margin_grid' | 'infinite_grid' | 'futures_grid' | 'spot_martingale'",
            );
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(strategyTypeSerialized)) {
                strategyTypeSerialized = strategyTypeSerialized.join(',');
            }
            localVarQueryParameters['strategy_type'] = strategyTypeSerialized;
        }

        if (opts.direction !== undefined) {
            let directionSerialized = ObjectSerializer.serialize(opts.direction, "'buy' | 'sell' | 'neutral'");
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(directionSerialized)) {
                directionSerialized = directionSerialized.join(',');
            }
            localVarQueryParameters['direction'] = directionSerialized;
        }

        if (opts.investAmount !== undefined) {
            let investAmountSerialized = ObjectSerializer.serialize(opts.investAmount, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(investAmountSerialized)) {
                investAmountSerialized = investAmountSerialized.join(',');
            }
            localVarQueryParameters['invest_amount'] = investAmountSerialized;
        }

        if (opts.scene !== undefined) {
            let sceneSerialized = ObjectSerializer.serialize(opts.scene, "'top1' | 'bundle' | 'filter' | 'refresh'");
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(sceneSerialized)) {
                sceneSerialized = sceneSerialized.join(',');
            }
            localVarQueryParameters['scene'] = sceneSerialized;
        }

        if (opts.refreshRecommendationId !== undefined) {
            let refreshRecommendationIdSerialized = ObjectSerializer.serialize(opts.refreshRecommendationId, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(refreshRecommendationIdSerialized)) {
                refreshRecommendationIdSerialized = refreshRecommendationIdSerialized.join(',');
            }
            localVarQueryParameters['refresh_recommendation_id'] = refreshRecommendationIdSerialized;
        }

        if (opts.limit !== undefined) {
            let limitSerialized = ObjectSerializer.serialize(opts.limit, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(limitSerialized)) {
                limitSerialized = limitSerialized.join(',');
            }
            localVarQueryParameters['limit'] = limitSerialized;
        }

        if (opts.maxDrawdownLte !== undefined) {
            let maxDrawdownLteSerialized = ObjectSerializer.serialize(opts.maxDrawdownLte, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(maxDrawdownLteSerialized)) {
                maxDrawdownLteSerialized = maxDrawdownLteSerialized.join(',');
            }
            localVarQueryParameters['max_drawdown_lte'] = maxDrawdownLteSerialized;
        }

        if (opts.backtestAprGte !== undefined) {
            let backtestAprGteSerialized = ObjectSerializer.serialize(opts.backtestAprGte, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(backtestAprGteSerialized)) {
                backtestAprGteSerialized = backtestAprGteSerialized.join(',');
            }
            localVarQueryParameters['backtest_apr_gte'] = backtestAprGteSerialized;
        }

        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubDiscoverSuccessResponse>(config, 'AIHubDiscoverSuccessResponse', authSettings);
    }

    /**
     * Create a spot grid strategy based on the incoming parameters.
     * @summary Create spot grid
     * @param spotGridCreateRequest
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async postAIHubSpotGridCreate(
        spotGridCreateRequest: SpotGridCreateRequest,
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubCreateSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/spot-grid/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'spotGridCreateRequest' is not null or undefined
        if (spotGridCreateRequest === null || spotGridCreateRequest === undefined) {
            throw new Error(
                'Required parameter spotGridCreateRequest was null or undefined when calling postAIHubSpotGridCreate.',
            );
        }

        opts = opts || {};
        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(spotGridCreateRequest, 'SpotGridCreateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubCreateSuccessResponse>(config, 'AIHubCreateSuccessResponse', authSettings);
    }

    /**
     * Create a leverage grid strategy based on the passed parameters.
     * @summary Create a lever grid
     * @param marginGridCreateRequest
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async postAIHubMarginGridCreate(
        marginGridCreateRequest: MarginGridCreateRequest,
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubCreateSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/margin-grid/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'marginGridCreateRequest' is not null or undefined
        if (marginGridCreateRequest === null || marginGridCreateRequest === undefined) {
            throw new Error(
                'Required parameter marginGridCreateRequest was null or undefined when calling postAIHubMarginGridCreate.',
            );
        }

        opts = opts || {};
        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(marginGridCreateRequest, 'MarginGridCreateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubCreateSuccessResponse>(config, 'AIHubCreateSuccessResponse', authSettings);
    }

    /**
     * Create an infinite grid strategy based on passed parameters.
     * @summary Create infinite grid
     * @param infiniteGridCreateRequest
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async postAIHubInfiniteGridCreate(
        infiniteGridCreateRequest: InfiniteGridCreateRequest,
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubCreateSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/infinite-grid/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'infiniteGridCreateRequest' is not null or undefined
        if (infiniteGridCreateRequest === null || infiniteGridCreateRequest === undefined) {
            throw new Error(
                'Required parameter infiniteGridCreateRequest was null or undefined when calling postAIHubInfiniteGridCreate.',
            );
        }

        opts = opts || {};
        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(infiniteGridCreateRequest, 'InfiniteGridCreateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubCreateSuccessResponse>(config, 'AIHubCreateSuccessResponse', authSettings);
    }

    /**
     * Create a contract grid strategy based on the incoming parameters.
     * @summary Create a contract grid
     * @param futuresGridCreateRequest
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async postAIHubFuturesGridCreate(
        futuresGridCreateRequest: FuturesGridCreateRequest,
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubCreateSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/futures-grid/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'futuresGridCreateRequest' is not null or undefined
        if (futuresGridCreateRequest === null || futuresGridCreateRequest === undefined) {
            throw new Error(
                'Required parameter futuresGridCreateRequest was null or undefined when calling postAIHubFuturesGridCreate.',
            );
        }

        opts = opts || {};
        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(futuresGridCreateRequest, 'FuturesGridCreateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubCreateSuccessResponse>(config, 'AIHubCreateSuccessResponse', authSettings);
    }

    /**
     * Create a spot Martin strategy based on the passed parameters.
     * @summary Create Spot Martin
     * @param spotMartingaleCreateRequest
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async postAIHubSpotMartingaleCreate(
        spotMartingaleCreateRequest: SpotMartingaleCreateRequest,
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubCreateSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/spot-martingale/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'spotMartingaleCreateRequest' is not null or undefined
        if (spotMartingaleCreateRequest === null || spotMartingaleCreateRequest === undefined) {
            throw new Error(
                'Required parameter spotMartingaleCreateRequest was null or undefined when calling postAIHubSpotMartingaleCreate.',
            );
        }

        opts = opts || {};
        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(spotMartingaleCreateRequest, 'SpotMartingaleCreateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubCreateSuccessResponse>(config, 'AIHubCreateSuccessResponse', authSettings);
    }

    /**
     * Create a contract Martin strategy based on the input parameters.
     * @summary Create contract martin
     * @param contractMartingaleCreateRequest
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async postAIHubContractMartingaleCreate(
        contractMartingaleCreateRequest: ContractMartingaleCreateRequest,
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubCreateSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/contract-martingale/create';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'contractMartingaleCreateRequest' is not null or undefined
        if (contractMartingaleCreateRequest === null || contractMartingaleCreateRequest === undefined) {
            throw new Error(
                'Required parameter contractMartingaleCreateRequest was null or undefined when calling postAIHubContractMartingaleCreate.',
            );
        }

        opts = opts || {};
        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(contractMartingaleCreateRequest, 'ContractMartingaleCreateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubCreateSuccessResponse>(config, 'AIHubCreateSuccessResponse', authSettings);
    }

    /**
     * Query the list of AIHub strategies currently running by the user, and support filtering by strategy type, trading pair and paging conditions.
     * @summary Query the list of running policies
     * @param opts Optional parameters
     * @param opts.strategyType Filter by policy type
     * @param opts.market Filter by trading pair
     * @param opts.page Page number, default 1
     * @param opts.pageSize Paging size, default 20, maximum 50
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async getAIHubPortfolioRunning(opts?: {
        strategyType?:
            | 'spot_grid'
            | 'margin_grid'
            | 'infinite_grid'
            | 'futures_grid'
            | 'spot_martingale'
            | 'contract_martingale';
        market?: string;
        page?: number;
        pageSize?: number;
        xGateServiceId?: string;
        xGateAppLang?: string;
        xRequestId?: string;
        xTraceId?: string;
    }): Promise<{ response: AxiosResponse; body: AIHubPortfolioRunningSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/portfolio/running';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.strategyType !== undefined) {
            let strategyTypeSerialized = ObjectSerializer.serialize(
                opts.strategyType,
                "'spot_grid' | 'margin_grid' | 'infinite_grid' | 'futures_grid' | 'spot_martingale' | 'contract_martingale'",
            );
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(strategyTypeSerialized)) {
                strategyTypeSerialized = strategyTypeSerialized.join(',');
            }
            localVarQueryParameters['strategy_type'] = strategyTypeSerialized;
        }

        if (opts.market !== undefined) {
            let marketSerialized = ObjectSerializer.serialize(opts.market, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(marketSerialized)) {
                marketSerialized = marketSerialized.join(',');
            }
            localVarQueryParameters['market'] = marketSerialized;
        }

        if (opts.page !== undefined) {
            let pageSerialized = ObjectSerializer.serialize(opts.page, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(pageSerialized)) {
                pageSerialized = pageSerialized.join(',');
            }
            localVarQueryParameters['page'] = pageSerialized;
        }

        if (opts.pageSize !== undefined) {
            let pageSizeSerialized = ObjectSerializer.serialize(opts.pageSize, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(pageSizeSerialized)) {
                pageSizeSerialized = pageSizeSerialized.join(',');
            }
            localVarQueryParameters['page_size'] = pageSizeSerialized;
        }

        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubPortfolioRunningSuccessResponse>(
            config,
            'AIHubPortfolioRunningSuccessResponse',
            authSettings,
        );
    }

    /**
     * Both `strategy_id` and `strategy_type` must be passed in the request, where `strategy_type` is used to distribute to the underlying detailed implementation by strategy type.
     * @summary Query order policy details
     * @param strategyId Policy ID
     * @param strategyType Policy type; used for underlying detail distribution
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async getAIHubPortfolioDetail(
        strategyId: string,
        strategyType:
            | 'spot_grid'
            | 'margin_grid'
            | 'infinite_grid'
            | 'futures_grid'
            | 'spot_martingale'
            | 'contract_martingale',
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubPortfolioDetailSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/portfolio/detail';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'strategyId' is not null or undefined
        if (strategyId === null || strategyId === undefined) {
            throw new Error(
                'Required parameter strategyId was null or undefined when calling getAIHubPortfolioDetail.',
            );
        }

        // verify required parameter 'strategyType' is not null or undefined
        if (strategyType === null || strategyType === undefined) {
            throw new Error(
                'Required parameter strategyType was null or undefined when calling getAIHubPortfolioDetail.',
            );
        }

        opts = opts || {};
        let strategyIdSerialized = ObjectSerializer.serialize(strategyId, 'string');
        // For array query parameters with style:form and explode:false, convert to comma-separated string
        if (Array.isArray(strategyIdSerialized)) {
            strategyIdSerialized = strategyIdSerialized.join(',');
        }
        localVarQueryParameters['strategy_id'] = strategyIdSerialized;

        let strategyTypeSerialized = ObjectSerializer.serialize(
            strategyType,
            "'spot_grid' | 'margin_grid' | 'infinite_grid' | 'futures_grid' | 'spot_martingale' | 'contract_martingale'",
        );
        // For array query parameters with style:form and explode:false, convert to comma-separated string
        if (Array.isArray(strategyTypeSerialized)) {
            strategyTypeSerialized = strategyTypeSerialized.join(',');
        }
        localVarQueryParameters['strategy_type'] = strategyTypeSerialized;

        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubPortfolioDetailSuccessResponse>(
            config,
            'AIHubPortfolioDetailSuccessResponse',
            authSettings,
        );
    }

    /**
     * Only one policy is allowed to be terminated per request. Risk warning and secondary confirmation are borne by the upper layer of OpenClaw; this interface is only responsible for executing stop.
     * @summary Terminate a single running policy
     * @param aIHubPortfolioStopRequest
     * @param opts Optional parameters
     * @param opts.xGateServiceId Call source identifier; injected by APIv4 if necessary
     * @param opts.xGateAppLang Language context, such as &#x60;zh-CN&#x60; / &#x60;en-US&#x60;
     * @param opts.xRequestId Request link ID; caller can transmit transparently
     * @param opts.xTraceId trace header; can be generated uniformly by APIv4
     */
    public async postAIHubPortfolioStop(
        aIHubPortfolioStopRequest: AIHubPortfolioStopRequest,
        opts?: { xGateServiceId?: string; xGateAppLang?: string; xRequestId?: string; xTraceId?: string },
    ): Promise<{ response: AxiosResponse; body: AIHubPortfolioStopSuccessResponse }> {
        const localVarPath = this.client.basePath + '/bot/portfolio/stop';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'aIHubPortfolioStopRequest' is not null or undefined
        if (aIHubPortfolioStopRequest === null || aIHubPortfolioStopRequest === undefined) {
            throw new Error(
                'Required parameter aIHubPortfolioStopRequest was null or undefined when calling postAIHubPortfolioStop.',
            );
        }

        opts = opts || {};
        if (opts.xGateServiceId !== undefined) {
            localVarHeaderParams['X-Gate-Service-Id'] = ObjectSerializer.serialize(opts.xGateServiceId, 'string');
        }
        if (opts.xGateAppLang !== undefined) {
            localVarHeaderParams['X-Gate-AppLang'] = ObjectSerializer.serialize(opts.xGateAppLang, 'string');
        }
        if (opts.xRequestId !== undefined) {
            localVarHeaderParams['X-Request-Id'] = ObjectSerializer.serialize(opts.xRequestId, 'string');
        }
        if (opts.xTraceId !== undefined) {
            localVarHeaderParams['X-Trace-Id'] = ObjectSerializer.serialize(opts.xTraceId, 'string');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(aIHubPortfolioStopRequest, 'AIHubPortfolioStopRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<AIHubPortfolioStopSuccessResponse>(
            config,
            'AIHubPortfolioStopSuccessResponse',
            authSettings,
        );
    }
}
