/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-locals */
import { InlineResponse20012 } from '../model/inlineResponse20012';
import { InlineResponse20013 } from '../model/inlineResponse20013';
import { InlineResponse20014 } from '../model/inlineResponse20014';
import { ObjectSerializer } from '../model/models';
import { ApiClient } from './apiClient';
import { AxiosRequestConfig, AxiosResponse } from 'axios';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export class DefaultApi {
    protected client: ApiClient;

    constructor(client?: ApiClient) {
        if (client) {
            this.client = client;
        } else {
            this.client = new ApiClient();
        }
    }

    /**
     * Query user\'s Activity Center entry information, including activity icon and redirect link
     * @summary My activity entry
     */
    public async getMyActivityEntry(): Promise<{ response: AxiosResponse; body: InlineResponse20012 }> {
        const localVarPath = this.client.basePath + '/rewards/activity/my-activity-entry';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<InlineResponse20012>(config, 'InlineResponse20012', authSettings);
    }

    /**
     * Query recommended activity list from Activity Center, supports pagination and sorting
     * @summary Recommended activity list
     * @param opts Optional parameters
     * @param opts.recommendType Recommendation type: hot for popular activities, type for filtering by activity type (type_ids), scenario for matching by activity name
     * @param opts.typeIds Activity type ID, multiple IDs separated by commas (supports filtering by activity type through this field)
     * @param opts.keywords Activity name. When scenario type is used, keyword matching is applied
     * @param opts.page Page number, starting from 1
     * @param opts.pageSize Items per page
     * @param opts.sortBy Sort order, e.g., hot for sorting by popularity
     */
    public async listActivities(opts?: {
        recommendType?: string;
        typeIds?: string;
        keywords?: string;
        page?: number;
        pageSize?: number;
        sortBy?: string;
    }): Promise<{ response: AxiosResponse; body: InlineResponse20013 }> {
        const localVarPath = this.client.basePath + '/rewards/activity/activity-list';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.recommendType !== undefined) {
            let recommendTypeSerialized = ObjectSerializer.serialize(opts.recommendType, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(recommendTypeSerialized)) {
                recommendTypeSerialized = recommendTypeSerialized.join(',');
            }
            localVarQueryParameters['recommend_type'] = recommendTypeSerialized;
        }

        if (opts.typeIds !== undefined) {
            let typeIdsSerialized = ObjectSerializer.serialize(opts.typeIds, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(typeIdsSerialized)) {
                typeIdsSerialized = typeIdsSerialized.join(',');
            }
            localVarQueryParameters['type_ids'] = typeIdsSerialized;
        }

        if (opts.keywords !== undefined) {
            let keywordsSerialized = ObjectSerializer.serialize(opts.keywords, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(keywordsSerialized)) {
                keywordsSerialized = keywordsSerialized.join(',');
            }
            localVarQueryParameters['keywords'] = keywordsSerialized;
        }

        if (opts.page !== undefined) {
            let pageSerialized = ObjectSerializer.serialize(opts.page, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(pageSerialized)) {
                pageSerialized = pageSerialized.join(',');
            }
            localVarQueryParameters['page'] = pageSerialized;
        }

        if (opts.pageSize !== undefined) {
            let pageSizeSerialized = ObjectSerializer.serialize(opts.pageSize, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(pageSizeSerialized)) {
                pageSizeSerialized = pageSizeSerialized.join(',');
            }
            localVarQueryParameters['page_size'] = pageSizeSerialized;
        }

        if (opts.sortBy !== undefined) {
            let sortBySerialized = ObjectSerializer.serialize(opts.sortBy, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(sortBySerialized)) {
                sortBySerialized = sortBySerialized.join(',');
            }
            localVarQueryParameters['sort_by'] = sortBySerialized;
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<InlineResponse20013>(config, 'InlineResponse20013', authSettings);
    }

    /**
     * Query all activity types supported by Activity Center
     * @summary Activity type list
     */
    public async listActivityTypes(): Promise<{ response: AxiosResponse; body: InlineResponse20014 }> {
        const localVarPath = this.client.basePath + '/rewards/activity/activity-type';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = [];
        return this.client.request<InlineResponse20014>(config, 'InlineResponse20014', authSettings);
    }
}
