/**
 * Gate API
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-locals */
import { Categories } from '../model/categories';
import { ContractDetail } from '../model/contractDetail';
import { CreateOrder } from '../model/createOrder';
import { CreateTransaction } from '../model/createTransaction';
import { CreateUserResp } from '../model/createUserResp';
import { DeletePosition } from '../model/deletePosition';
import { Klines } from '../model/klines';
import { Mt5Account } from '../model/mt5Account';
import { OrderHistoryList } from '../model/orderHistoryList';
import { OrderList } from '../model/orderList';
import { PositionHistoryList } from '../model/positionHistoryList';
import { PositionList } from '../model/positionList';
import { Symbols } from '../model/symbols';
import { TradFiClosePositionRequest } from '../model/tradFiClosePositionRequest';
import { TradFiError } from '../model/tradFiError';
import { TradFiOrderRequest } from '../model/tradFiOrderRequest';
import { TradFiOrderUpdateRequest } from '../model/tradFiOrderUpdateRequest';
import { TradFiPositionUpdateRequest } from '../model/tradFiPositionUpdateRequest';
import { TradFiTicker } from '../model/tradFiTicker';
import { TradFiTransactionRequest } from '../model/tradFiTransactionRequest';
import { TransactionList } from '../model/transactionList';
import { UpdateOrder } from '../model/updateOrder';
import { UpdatePosition } from '../model/updatePosition';
import { UserAssetResp } from '../model/userAssetResp';
import { ObjectSerializer } from '../model/models';
import { ApiClient } from './apiClient';
import { AxiosRequestConfig, AxiosResponse } from 'axios';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export class TradFiApi {
    protected client: ApiClient;

    constructor(client?: ApiClient) {
        if (client) {
            this.client = client;
        } else {
            this.client = new ApiClient();
        }
    }

    /**
     *
     * @summary Query MT5 account information
     */
    public async queryMt5AccountInfo(): Promise<{ response: AxiosResponse; body: Mt5Account }> {
        const localVarPath = this.client.basePath + '/tradfi/users/mt5-account';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<Mt5Account>(config, 'Mt5Account', authSettings);
    }

    /**
     *
     * @summary Query trading symbol categories
     */
    public async queryCategories(): Promise<{ response: AxiosResponse; body: Categories }> {
        const localVarPath = this.client.basePath + '/tradfi/symbols/categories';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = [];
        return this.client.request<Categories>(config, 'Categories', authSettings);
    }

    /**
     *
     * @summary Query trading symbol list
     */
    public async querySymbols(): Promise<{ response: AxiosResponse; body: Symbols }> {
        const localVarPath = this.client.basePath + '/tradfi/symbols';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = [];
        return this.client.request<Symbols>(config, 'Symbols', authSettings);
    }

    /**
     *
     * @summary Query trading symbol details
     * @param symbols Trading symbol code list (comma-separated, max 10 symbols)
     */
    public async querySymbolDetail(symbols: string): Promise<{ response: AxiosResponse; body: ContractDetail }> {
        const localVarPath = this.client.basePath + '/tradfi/symbols/detail';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'symbols' is not null or undefined
        if (symbols === null || symbols === undefined) {
            throw new Error('Required parameter symbols was null or undefined when calling querySymbolDetail.');
        }

        let symbolsSerialized = ObjectSerializer.serialize(symbols, 'string');
        // For array query parameters with style:form and explode:false, convert to comma-separated string
        if (Array.isArray(symbolsSerialized)) {
            symbolsSerialized = symbolsSerialized.join(',');
        }
        localVarQueryParameters['symbols'] = symbolsSerialized;

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<ContractDetail>(config, 'ContractDetail', authSettings);
    }

    /**
     *
     * @summary Query trading symbol klines
     * @param symbol Trading symbol code
     * @param klineType Kline type (time period)
     * @param opts Optional parameters
     * @param opts.beginTime Start time (Unix timestamp in seconds)
     * @param opts.endTime End time (Unix timestamp in seconds)
     * @param opts.limit Kline limit (max 500, error if exceeded)
     */
    public async querySymbolKline(
        symbol: string,
        klineType: '1m' | '15m' | '1h' | '4h' | '1d' | '7d' | '30d',
        opts?: { beginTime?: number; endTime?: number; limit?: number },
    ): Promise<{ response: AxiosResponse; body: Klines }> {
        const localVarPath =
            this.client.basePath +
            '/tradfi/symbols/{symbol}/klines'.replace('{' + 'symbol' + '}', encodeURIComponent(String(symbol)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'symbol' is not null or undefined
        if (symbol === null || symbol === undefined) {
            throw new Error('Required parameter symbol was null or undefined when calling querySymbolKline.');
        }

        // verify required parameter 'klineType' is not null or undefined
        if (klineType === null || klineType === undefined) {
            throw new Error('Required parameter klineType was null or undefined when calling querySymbolKline.');
        }

        opts = opts || {};
        let klineTypeSerialized = ObjectSerializer.serialize(
            klineType,
            "'1m' | '15m' | '1h' | '4h' | '1d' | '7d' | '30d'",
        );
        // For array query parameters with style:form and explode:false, convert to comma-separated string
        if (Array.isArray(klineTypeSerialized)) {
            klineTypeSerialized = klineTypeSerialized.join(',');
        }
        localVarQueryParameters['kline_type'] = klineTypeSerialized;

        if (opts.beginTime !== undefined) {
            let beginTimeSerialized = ObjectSerializer.serialize(opts.beginTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(beginTimeSerialized)) {
                beginTimeSerialized = beginTimeSerialized.join(',');
            }
            localVarQueryParameters['begin_time'] = beginTimeSerialized;
        }

        if (opts.endTime !== undefined) {
            let endTimeSerialized = ObjectSerializer.serialize(opts.endTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(endTimeSerialized)) {
                endTimeSerialized = endTimeSerialized.join(',');
            }
            localVarQueryParameters['end_time'] = endTimeSerialized;
        }

        if (opts.limit !== undefined) {
            let limitSerialized = ObjectSerializer.serialize(opts.limit, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(limitSerialized)) {
                limitSerialized = limitSerialized.join(',');
            }
            localVarQueryParameters['limit'] = limitSerialized;
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = [];
        return this.client.request<Klines>(config, 'Klines', authSettings);
    }

    /**
     *
     * @summary Query trading symbol ticker
     * @param symbol Trading symbol code
     */
    public async querySymbolTicker(symbol: string): Promise<{ response: AxiosResponse; body: TradFiTicker }> {
        const localVarPath =
            this.client.basePath +
            '/tradfi/symbols/{symbol}/tickers'.replace('{' + 'symbol' + '}', encodeURIComponent(String(symbol)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'symbol' is not null or undefined
        if (symbol === null || symbol === undefined) {
            throw new Error('Required parameter symbol was null or undefined when calling querySymbolTicker.');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = [];
        return this.client.request<TradFiTicker>(config, 'TradFiTicker', authSettings);
    }

    /**
     *
     * @summary Create TradFi user
     */
    public async createTradFiUser(): Promise<{ response: AxiosResponse; body: CreateUserResp }> {
        const localVarPath = this.client.basePath + '/tradfi/users';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<CreateUserResp>(config, 'CreateUserResp', authSettings);
    }

    /**
     * Query account assets
     * @summary Query account assets
     */
    public async queryUserAssets(): Promise<{ response: AxiosResponse; body: UserAssetResp }> {
        const localVarPath = this.client.basePath + '/tradfi/users/assets';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<UserAssetResp>(config, 'UserAssetResp', authSettings);
    }

    /**
     *
     * @summary Query Fund Transfer In/Out Records
     * @param opts Optional parameters
     * @param opts.beginTime Start Time (Second-level Timestamp)
     * @param opts.endTime End Time (Second-level Timestamp)
     * @param opts.type Transaction Type (deposit - transfer in, withdraw - transfer out, dividend - dividend payment, fill_negative - cover negative balance)
     * @param opts.page page number
     * @param opts.pageSize Number per page, default 10, maximum 50
     */
    public async queryTransaction(opts?: {
        beginTime?: number;
        endTime?: number;
        type?: 'deposit' | 'withdraw' | 'dividend' | 'fill_negative';
        page?: number;
        pageSize?: number;
    }): Promise<{ response: AxiosResponse; body: TransactionList }> {
        const localVarPath = this.client.basePath + '/tradfi/transactions';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.beginTime !== undefined) {
            let beginTimeSerialized = ObjectSerializer.serialize(opts.beginTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(beginTimeSerialized)) {
                beginTimeSerialized = beginTimeSerialized.join(',');
            }
            localVarQueryParameters['begin_time'] = beginTimeSerialized;
        }

        if (opts.endTime !== undefined) {
            let endTimeSerialized = ObjectSerializer.serialize(opts.endTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(endTimeSerialized)) {
                endTimeSerialized = endTimeSerialized.join(',');
            }
            localVarQueryParameters['end_time'] = endTimeSerialized;
        }

        if (opts.type !== undefined) {
            let typeSerialized = ObjectSerializer.serialize(
                opts.type,
                "'deposit' | 'withdraw' | 'dividend' | 'fill_negative'",
            );
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(typeSerialized)) {
                typeSerialized = typeSerialized.join(',');
            }
            localVarQueryParameters['type'] = typeSerialized;
        }

        if (opts.page !== undefined) {
            let pageSerialized = ObjectSerializer.serialize(opts.page, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(pageSerialized)) {
                pageSerialized = pageSerialized.join(',');
            }
            localVarQueryParameters['page'] = pageSerialized;
        }

        if (opts.pageSize !== undefined) {
            let pageSizeSerialized = ObjectSerializer.serialize(opts.pageSize, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(pageSizeSerialized)) {
                pageSizeSerialized = pageSizeSerialized.join(',');
            }
            localVarQueryParameters['page_size'] = pageSizeSerialized;
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<TransactionList>(config, 'TransactionList', authSettings);
    }

    /**
     *
     * @summary Fund Deposit and Withdrawal
     * @param tradFiTransactionRequest
     */
    public async createTransaction(
        tradFiTransactionRequest: TradFiTransactionRequest,
    ): Promise<{ response: AxiosResponse; body: CreateTransaction }> {
        const localVarPath = this.client.basePath + '/tradfi/transactions';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'tradFiTransactionRequest' is not null or undefined
        if (tradFiTransactionRequest === null || tradFiTransactionRequest === undefined) {
            throw new Error(
                'Required parameter tradFiTransactionRequest was null or undefined when calling createTransaction.',
            );
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(tradFiTransactionRequest, 'TradFiTransactionRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<CreateTransaction>(config, 'CreateTransaction', authSettings);
    }

    /**
     *
     * @summary Query active order list
     */
    public async queryOrderList(): Promise<{ response: AxiosResponse; body: OrderList }> {
        const localVarPath = this.client.basePath + '/tradfi/orders';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<OrderList>(config, 'OrderList', authSettings);
    }

    /**
     *
     * @summary Create an order
     * @param tradFiOrderRequest
     */
    public async createTradFiOrder(
        tradFiOrderRequest: TradFiOrderRequest,
    ): Promise<{ response: AxiosResponse; body: CreateOrder }> {
        const localVarPath = this.client.basePath + '/tradfi/orders';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'tradFiOrderRequest' is not null or undefined
        if (tradFiOrderRequest === null || tradFiOrderRequest === undefined) {
            throw new Error(
                'Required parameter tradFiOrderRequest was null or undefined when calling createTradFiOrder.',
            );
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(tradFiOrderRequest, 'TradFiOrderRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<CreateOrder>(config, 'CreateOrder', authSettings);
    }

    /**
     *
     * @summary Modify order
     * @param orderId Order ID
     * @param tradFiOrderUpdateRequest
     */
    public async updateOrder(
        orderId: number,
        tradFiOrderUpdateRequest: TradFiOrderUpdateRequest,
    ): Promise<{ response: AxiosResponse; body: UpdateOrder }> {
        const localVarPath =
            this.client.basePath +
            '/tradfi/orders/{order_id}'.replace('{' + 'order_id' + '}', encodeURIComponent(String(orderId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'orderId' is not null or undefined
        if (orderId === null || orderId === undefined) {
            throw new Error('Required parameter orderId was null or undefined when calling updateOrder.');
        }

        // verify required parameter 'tradFiOrderUpdateRequest' is not null or undefined
        if (tradFiOrderUpdateRequest === null || tradFiOrderUpdateRequest === undefined) {
            throw new Error(
                'Required parameter tradFiOrderUpdateRequest was null or undefined when calling updateOrder.',
            );
        }

        const config: AxiosRequestConfig = {
            method: 'PUT',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(tradFiOrderUpdateRequest, 'TradFiOrderUpdateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<UpdateOrder>(config, 'UpdateOrder', authSettings);
    }

    /**
     *
     * @summary Cancel order
     * @param orderId Order ID
     */
    public async deleteOrder(orderId: number): Promise<{ response: AxiosResponse; body: object }> {
        const localVarPath =
            this.client.basePath +
            '/tradfi/orders/{order_id}'.replace('{' + 'order_id' + '}', encodeURIComponent(String(orderId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'orderId' is not null or undefined
        if (orderId === null || orderId === undefined) {
            throw new Error('Required parameter orderId was null or undefined when calling deleteOrder.');
        }

        const config: AxiosRequestConfig = {
            method: 'DELETE',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<object>(config, 'object', authSettings);
    }

    /**
     *
     * @summary Query historical order list
     * @param opts Optional parameters
     * @param opts.beginTime Start time (Unix timestamp in seconds), earliest query is one month ago
     * @param opts.endTime End time (Unix timestamp in seconds)
     * @param opts.symbol Currency pair
     * @param opts.side Order side (1&#x3D;sell, 2&#x3D;buy)
     */
    public async queryOrderHistoryList(opts?: {
        beginTime?: number;
        endTime?: number;
        symbol?: string;
        side?: 1 | 2;
    }): Promise<{ response: AxiosResponse; body: OrderHistoryList }> {
        const localVarPath = this.client.basePath + '/tradfi/orders/history';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.beginTime !== undefined) {
            let beginTimeSerialized = ObjectSerializer.serialize(opts.beginTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(beginTimeSerialized)) {
                beginTimeSerialized = beginTimeSerialized.join(',');
            }
            localVarQueryParameters['begin_time'] = beginTimeSerialized;
        }

        if (opts.endTime !== undefined) {
            let endTimeSerialized = ObjectSerializer.serialize(opts.endTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(endTimeSerialized)) {
                endTimeSerialized = endTimeSerialized.join(',');
            }
            localVarQueryParameters['end_time'] = endTimeSerialized;
        }

        if (opts.symbol !== undefined) {
            let symbolSerialized = ObjectSerializer.serialize(opts.symbol, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(symbolSerialized)) {
                symbolSerialized = symbolSerialized.join(',');
            }
            localVarQueryParameters['symbol'] = symbolSerialized;
        }

        if (opts.side !== undefined) {
            let sideSerialized = ObjectSerializer.serialize(opts.side, '1 | 2');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(sideSerialized)) {
                sideSerialized = sideSerialized.join(',');
            }
            localVarQueryParameters['side'] = sideSerialized;
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<OrderHistoryList>(config, 'OrderHistoryList', authSettings);
    }

    /**
     *
     * @summary Query active position list
     */
    public async queryPositionList(): Promise<{ response: AxiosResponse; body: PositionList }> {
        const localVarPath = this.client.basePath + '/tradfi/positions';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<PositionList>(config, 'PositionList', authSettings);
    }

    /**
     *
     * @summary Modify position
     * @param positionId Position ID
     * @param tradFiPositionUpdateRequest
     */
    public async updatePosition(
        positionId: number,
        tradFiPositionUpdateRequest: TradFiPositionUpdateRequest,
    ): Promise<{ response: AxiosResponse; body: UpdatePosition }> {
        const localVarPath =
            this.client.basePath +
            '/tradfi/positions/{position_id}'.replace(
                '{' + 'position_id' + '}',
                encodeURIComponent(String(positionId)),
            );
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'positionId' is not null or undefined
        if (positionId === null || positionId === undefined) {
            throw new Error('Required parameter positionId was null or undefined when calling updatePosition.');
        }

        // verify required parameter 'tradFiPositionUpdateRequest' is not null or undefined
        if (tradFiPositionUpdateRequest === null || tradFiPositionUpdateRequest === undefined) {
            throw new Error(
                'Required parameter tradFiPositionUpdateRequest was null or undefined when calling updatePosition.',
            );
        }

        const config: AxiosRequestConfig = {
            method: 'PUT',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(tradFiPositionUpdateRequest, 'TradFiPositionUpdateRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<UpdatePosition>(config, 'UpdatePosition', authSettings);
    }

    /**
     *
     * @summary Close position
     * @param positionId Position ID
     * @param tradFiClosePositionRequest
     */
    public async closePosition(
        positionId: number,
        tradFiClosePositionRequest: TradFiClosePositionRequest,
    ): Promise<{ response: AxiosResponse; body: DeletePosition }> {
        const localVarPath =
            this.client.basePath +
            '/tradfi/positions/{position_id}/close'.replace(
                '{' + 'position_id' + '}',
                encodeURIComponent(String(positionId)),
            );
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        // verify required parameter 'positionId' is not null or undefined
        if (positionId === null || positionId === undefined) {
            throw new Error('Required parameter positionId was null or undefined when calling closePosition.');
        }

        // verify required parameter 'tradFiClosePositionRequest' is not null or undefined
        if (tradFiClosePositionRequest === null || tradFiClosePositionRequest === undefined) {
            throw new Error(
                'Required parameter tradFiClosePositionRequest was null or undefined when calling closePosition.',
            );
        }

        const config: AxiosRequestConfig = {
            method: 'POST',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
            data: ObjectSerializer.serialize(tradFiClosePositionRequest, 'TradFiClosePositionRequest'),
        };

        const authSettings = ['apiv4'];
        return this.client.request<DeletePosition>(config, 'DeletePosition', authSettings);
    }

    /**
     *
     * @summary Query historical position list
     * @param opts Optional parameters
     * @param opts.beginTime Start Time (Unix Timestamp, seconds). The earliest queryable time is one month ago
     * @param opts.endTime End time (timestamp in seconds)
     * @param opts.symbol Trading symbol (e.g., EURUSD)
     * @param opts.positionDir Position direction (Long&#x3D;long position, Short&#x3D;short position)
     */
    public async queryPositionHistoryList(opts?: {
        beginTime?: number;
        endTime?: number;
        symbol?: string;
        positionDir?: 'Long' | 'Short';
    }): Promise<{ response: AxiosResponse; body: PositionHistoryList }> {
        const localVarPath = this.client.basePath + '/tradfi/positions/history';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.client.defaultHeaders);
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }

        opts = opts || {};
        if (opts.beginTime !== undefined) {
            let beginTimeSerialized = ObjectSerializer.serialize(opts.beginTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(beginTimeSerialized)) {
                beginTimeSerialized = beginTimeSerialized.join(',');
            }
            localVarQueryParameters['begin_time'] = beginTimeSerialized;
        }

        if (opts.endTime !== undefined) {
            let endTimeSerialized = ObjectSerializer.serialize(opts.endTime, 'number');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(endTimeSerialized)) {
                endTimeSerialized = endTimeSerialized.join(',');
            }
            localVarQueryParameters['end_time'] = endTimeSerialized;
        }

        if (opts.symbol !== undefined) {
            let symbolSerialized = ObjectSerializer.serialize(opts.symbol, 'string');
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(symbolSerialized)) {
                symbolSerialized = symbolSerialized.join(',');
            }
            localVarQueryParameters['symbol'] = symbolSerialized;
        }

        if (opts.positionDir !== undefined) {
            let positionDirSerialized = ObjectSerializer.serialize(opts.positionDir, "'Long' | 'Short'");
            // For array query parameters with style:form and explode:false, convert to comma-separated string
            if (Array.isArray(positionDirSerialized)) {
                positionDirSerialized = positionDirSerialized.join(',');
            }
            localVarQueryParameters['position_dir'] = positionDirSerialized;
        }

        const config: AxiosRequestConfig = {
            method: 'GET',
            params: localVarQueryParameters,
            headers: localVarHeaderParams,
            url: localVarPath,
        };

        const authSettings = ['apiv4'];
        return this.client.request<PositionHistoryList>(config, 'PositionHistoryList', authSettings);
    }
}
